export const HEALTH_DATA = [
  {
    id: "body-measurements",
    name: "Body Measurements",
    calculators: [
      { name: "ABSI Calculator", slug: "absi-calculator" },
      { name: "Body Fat Calculator", slug: "body-fat-calculator" },
      { name: "BSA Calculator", slug: "bsa-calculator" },
      { name: "FFMI Calculator", slug: "ffmi-calculator" },
      { name: "Ideal Weight Calculator", slug: "ideal-weight-calculator" },
      { name: "Adjusted Body Weight Calculator", slug: "adjusted-body-weight-calculator" },
      { name: "BAI Calculator", slug: "bai-calculator" },
      { name: "BRI Calculator", slug: "bri-calculator" },
      { name: "Ponderal Index Calculator", slug: "ponderal-index-calculator" },
      { name: "RFM Calculator", slug: "rfm-calculator" },
      { name: "Body Frame Size Calculator", slug: "body-frame-size-calculator" },
      { name: "Karvonen Formula Calculator", slug: "karvonen-formula-calculator" },
      { name: "Lean Body Mass Calculator", slug: "lean-body-mass-calculator" },
      { name: "Waist to Hip Ratio Calculator", slug: "waist-to-hip-ratio-calculator" },
      { name: "Waist to Height Ratio Calculator", slug: "waist-to-height-ratio-calculator" },
      { name: "Draw Length Calculator", slug: "draw-length-calculator" },
      { name: "Bedridden Patient Height Calculator", slug: "bedridden-patient-height-calculator" },
      { name: "Overweight Calculator", slug: "overweight-calculator" },
      { name: "Weight Loss Percentage Calculator", slug: "weight-loss-percentage-calculator" },
      { name: "Skinfold Body Fat Calculator", slug: "skinfold-body-fat-calculator" }
    ]
  },
  {
    id: "bmi",
    name: "BMI Calculators",
    calculators: [
      { name: "BMI Calculator", slug: "bmi-calculator" },
      { name: "BMI Calculator for Kids", slug: "bmi-calculator-for-kids" },
      { name: "Geriatric BMI Calculator", slug: "geriatric-bmi-calculator" },
      { name: "BMI Calculator for Men", slug: "bmi-calculator-for-men" },
      { name: "BMI Calculator for Women", slug: "bmi-calculator-for-women" },
      { name: "BMI Calculator for Teens", slug: "bmi-calculator-for-teens" },
      { name: "BMI Weight Loss Calculator", slug: "bmi-weight-loss-calculator" }
    ]
  },
  {
    id: "dietary",
    name: "Dietary Calculators",
    calculators: [
      { name: "BMR Calculator", slug: "bmr-calculator" },
      { name: "Calorie Calculator", slug: "calorie-calculator" },
      { name: "TDEE Calculator", slug: "tdee-calculator" },
      { name: "Protein Calculator", slug: "protein-calculator" },
      { name: "Macro Calculator", slug: "macro-calculator" },
      { name: "Added Sugar Intake Calculator", slug: "added-sugar-intake-calculator" },
      { name: "BEE Calculator", slug: "bee-calculator" },
      { name: "Harris-Benedict Calculator", slug: "harris-benedict-calculator" },
      { name: "Katch-McArdle Calculator", slug: "katch-mcardle-calculator" },
      { name: "Calorie Deficit Calculator", slug: "calorie-deficit-calculator" },
      { name: "Carb Calculator", slug: "carb-calculator" },
      { name: "Fat Intake Calculator", slug: "fat-intake-calculator" },
      { name: "Fiber Calculator", slug: "fiber-calculator" },
      { name: "Maintenance Calorie Calculator", slug: "maintenance-calorie-calculator" },
      { name: "IIFYM Calculator", slug: "iifym-calculator" },
      { name: "Keto Calculator", slug: "keto-calculator" },
      { name: "Net Carbs Calculator", slug: "net-carbs-calculator" },
      { name: "Meal Calorie Calculator", slug: "meal-calorie-calculator" },
      { name: "Sodium in Salt Calculator", slug: "sodium-in-salt-calculator" },
      { name: "Weight Gain Calculator", slug: "weight-gain-calculator" },
      { name: "Weight Watchers Points Calculator", slug: "weight-watchers-points-calculator" },
      { name: "RMR Calculator", slug: "rmr-calculator" },
      { name: "Vitamin A Calculator", slug: "vitamin-a-calculator" },
      { name: "Vitamin D Calculator", slug: "vitamin-d-calculator" },
      { name: "Micronutrient Calculator", slug: "micronutrient-calculator" }
    ]
  },
  {
    id: "diabetes",
    name: "Diabetes Calculators",
    calculators: [
      { name: "Blood Sugar Converter", slug: "blood-sugar-converter" },
      { name: "A1c Calculator", slug: "a1c-calculator" },
      { name: "HOMA-IR Calculator", slug: "homa-ir-calculator" },
      { name: "Diabetes Risk Calculator", slug: "diabetes-risk-calculator" },
      { name: "Diabetic Ketoacidosis Calculator", slug: "diabetic-ketoacidosis-calculator" },
      { name: "Estimated Average Glucose Calculator", slug: "estimated-average-glucose-calculator" },
      { name: "Glycemic Load Calculator", slug: "glycemic-load-calculator" },
      { name: "Insulin Dosage Calculator", slug: "insulin-dosage-calculator" },
      { name: "QUICKI Calculator", slug: "quicki-calculator" },
      { name: "Warsaw Method Calculator", slug: "warsaw-method-calculator" }
    ]
  },
  {
    id: "sleep",
    name: "Sleep Calculators",
    calculators: [
      { name: "Sleep Calculator", slug: "sleep-calculator" },
      { name: "Sleep Debt Calculator", slug: "sleep-debt-calculator" },
      { name: "AHI Calculator", slug: "ahi-calculator" },
      { name: "Epworth Sleepiness Scale Calculator", slug: "epworth-sleepiness-scale-calculator" },
      { name: "Pediatric Epworth Sleepiness Scale Calculator", slug: "pediatric-epworth-sleepiness-scale-calculator" },
      { name: "STOP-BANG Calculator", slug: "stop-bang-calculator" }
    ]
  },
  {
    id: "cardiovascular",
    name: "Cardiovascular Calculators",
    calculators: [
      { name: "Blood Pressure Calculator", slug: "blood-pressure-calculator" },
      { name: "Cardiac Output Calculator", slug: "cardiac-output-calculator" },
      { name: "Stroke Volume Calculator", slug: "stroke-volume-calculator" },
      { name: "6 Minute Walk Test Calculator", slug: "6-minute-walk-test-calculator" },
      { name: "ABI Calculator", slug: "abi-calculator" },
      { name: "Cardiac Index Calculator", slug: "cardiac-index-calculator" },
      { name: "Cerebral Perfusion Pressure Calculator", slug: "cerebral-perfusion-pressure-calculator" },
      { name: "CHA2DS2-Vasc Calculator", slug: "cha2ds2-vasc-calculator" },
      { name: "MAP Calculator", slug: "map-calculator" },
      { name: "QTc Calculator", slug: "qtc-calculator" },
      { name: "Rate Pressure Product Calculator", slug: "rate-pressure-product-calculator" },
      { name: "CVD Risk Calculator", slug: "cvd-risk-calculator" },
      { name: "Wells Score for PE", slug: "wells-score-for-pe" },
      { name: "Duke Treadmill Score Calculator", slug: "duke-treadmill-score-calculator" },
      { name: "ECG Heart Rate Calculator", slug: "ecg-heart-rate-calculator" },
      { name: "Framingham Risk Calculator", slug: "framingham-risk-calculator" },
      { name: "HAS-BLED Calculator", slug: "has-bled-calculator" },
      { name: "HEART Score Calculator", slug: "heart-score-calculator" },
      { name: "PERC Calculator", slug: "perc-calculator" },
      { name: "PVR Calculator", slug: "pvr-calculator" },
      { name: "TIMI Score for STEMI Calculator", slug: "timi-score-for-stemi-calculator" },
      { name: "RCRI Calculator", slug: "rcri-calculator" },
      { name: "Aortic Valve Area Calculator", slug: "aortic-valve-area-calculator" },
      { name: "GRACE Calculator", slug: "grace-calculator" },
      { name: "TIMI Score for UA/NSTEMI", slug: "timi-ua-nstemi-calculator" },
      { name: "DAPT Calculator", slug: "dapt-calculator" },
      { name: "Arterial Age Calculator", slug: "arterial-age-calculator" },
      { name: "Doppler Echo Cardiac Output Calculator", slug: "doppler-echo-cardiac-output-calculator" },
      { name: "EROA - Mitral Regurgitation Calculator", slug: "eroa-mitral-regurgitation-calculator" },
      { name: "Gorlin Formula Calculator", slug: "gorlin-formula-calculator" },
      { name: "Gupta Risk Calculator", slug: "gupta-risk-calculator" },
      { name: "ICH Volume Calculator", slug: "ich-volume-calculator" },
      { name: "Padua Score Calculator", slug: "padua-score-calculator" },
      { name: "ECG Boxes to Seconds Calculator", slug: "ecg-boxes-to-seconds-calculator" },
      { name: "Heart Failure Life Expectancy Calculator", slug: "heart-failure-life-expectancy-calculator" },
      { name: "LV Calculator", slug: "lv-calculator" },
      { name: "Mitral Valve Area Calculator", slug: "mitral-valve-area-calculator" },
      { name: "PISA Calculator", slug: "pisa-calculator" },
      { name: "Revised Geneva Score Calculator", slug: "revised-geneva-score-calculator" }
    ]
  },
  {
    id: "gynecology-pregnancy",
    name: "Gynecology & Pregnancy",
    calculators: [
      { name: "Due Date Calculator", slug: "due-date-calculator" },
      { name: "Ovulation Calculator", slug: "ovulation-calculator" },
      { name: "Pregnancy Weight Gain Calculator", slug: "pregnancy-weight-gain-calculator" },
      { name: "hCG Levels Calculator", slug: "hcg-levels-calculator" },
      { name: "Fertility by Age Calculator", slug: "fertility-by-age-calculator" },
      { name: "BBT Calculator", slug: "bbt-calculator" },
      { name: "Bishop Score Calculator", slug: "bishop-score-calculator" },
      { name: "Breastfeeding Calorie Calculator", slug: "breastfeeding-calorie-calculator" },
      { name: "Conception Calculator", slug: "conception-calculator" },
      { name: "Gestational Age Calculator", slug: "gestational-age-calculator" },
      { name: "Implantation Calculator", slug: "implantation-calculator" },
      { name: "Luteal Phase Calculator", slug: "luteal-phase-calculator" },
      { name: "Pearl Index Calculator", slug: "pearl-index-calculator" },
      { name: "Pregnancy Test Calculator", slug: "pregnancy-test-calculator" },
      { name: "Reverse Due Date Calculator", slug: "reverse-due-date-calculator" },
      { name: "Clomid Ovulation Calculator", slug: "clomid-ovulation-calculator" },
      { name: "Crown-rump Length Calculator", slug: "crown-rump-length-calculator" },
      { name: "Period Calculator", slug: "period-calculator" },
      { name: "IVF Due Date Calculator", slug: "ivf-due-date-calculator" },
      { name: "Mean Sac Diameter Calculator", slug: "mean-sac-diameter-calculator" },
      { name: "Flange Size Calculator", slug: "flange-size-calculator" },
      { name: "Fundal Height Calculator", slug: "fundal-height-calculator" },
      { name: "Progesterone to Estrogen Ratio Calculator", slug: "progesterone-to-estrogen-ratio-calculator" },
      { name: "Chances of Having Twins Calculator", slug: "chances-of-having-twins-calculator" },
      { name: "VBAC Calculator", slug: "vbac-calculator" },
      { name: "Birth Control Calculator", slug: "birth-control-calculator" },
      { name: "Breast Cancer Risk Calculator", slug: "breast-cancer-risk-calculator" },
      { name: "Breast Cancer Recurrence Risk Calculator", slug: "breast-cancer-recurrence-risk-calculator" },
      { name: "Egg Freezing Calculator", slug: "egg-freezing-calculator" },
      { name: "MCA Calculator", slug: "mca-calculator" },
      { name: "Nuchal Translucency Calculator", slug: "nuchal-translucency-calculator" },
      { name: "Sperm Analysis Calculator", slug: "sperm-analysis-calculator" },
      { name: "Stillbirth Risk Calculator", slug: "stillbirth-risk-calculator" },
      { name: "Testosterone to Estradiol Ratio Calculator", slug: "testosterone-to-estradiol-ratio-calculator" },
      { name: "VTE Risk Score Calculator in Pregnancy", slug: "vte-risk-pregnancy-calculator" }
    ]
  },
  {
    id: "addiction-medicine",
    name: "Addiction Medicine",
    calculators: [
      { name: "BAC Calculator", slug: "bac-calculator" },
      { name: "Pack Year Calculator", slug: "pack-year-calculator" },
      { name: "Alcohol Unit Calculator", slug: "alcohol-unit-calculator" },
      { name: "Audit-C Calculator", slug: "audit-c-calculator" },
      { name: "Audit Score Calculator", slug: "audit-score-calculator" },
      { name: "Caffeine Calculator", slug: "caffeine-calculator" },
      { name: "Cigarette Calculator", slug: "cigarette-calculator" },
      { name: "CIWA Calculator", slug: "ciwa-calculator" },
      { name: "DUDIT Calculator", slug: "dudit-calculator" },
      { name: "EtG Calculator", slug: "etg-calculator" },
      { name: "Fagerstrom Test Calculator", slug: "fagerstrom-test-calculator" },
      { name: "HSI Calculator", slug: "hsi-calculator" },
      { name: "Addiction Calculator", slug: "addiction-calculator" },
      { name: "Finnegan Score Calculator", slug: "finnegan-score-calculator" },
      { name: "Smoking Recovery Calculator", slug: "smoking-recovery-calculator" },
      { name: "Sobriety Calculator", slug: "sobriety-calculator" },
      { name: "Standard Drink Calculator", slug: "standard-drink-calculator" }
    ]
  },
  {
    id: "urology-nephrology",
    name: "Urology & Nephrology",
    calculators: [
      { name: "GFR Calculator", slug: "gfr-calculator" },
      { name: "Creatinine Clearance Calculator", slug: "creatinine-clearance-calculator" },
      { name: "Adrenal Washout Calculator", slug: "adrenal-washout-calculator" },
      { name: "Albumin Creatinine Ratio Calculator", slug: "albumin-creatinine-ratio-calculator" },
      { name: "Bladder Volume Calculator", slug: "bladder-volume-calculator" },
      { name: "BUN Creatinine Ratio Calculator", slug: "bun-creatinine-ratio-calculator" },
      { name: "FENa Calculator", slug: "fena-calculator" },
      { name: "FEUrea Calculator", slug: "feurea-calculator" },
      { name: "Kidney Failure Risk Calculator", slug: "kidney-failure-risk-calculator" },
      { name: "PSA Density Calculator", slug: "psa-density-calculator" },
      { name: "PSA Doubling Time Calculator", slug: "psa-doubling-time-calculator" },
      { name: "Urine Output Calculator", slug: "urine-output-calculator" },
      { name: "EORTC Bladder Cancer Calculator", slug: "eortc-bladder-cancer-calculator" },
      { name: "Kidney STONE Calculator", slug: "kidney-stone-calculator" },
      { name: "Kt/V Calculator Daugirdas", slug: "ktv-daugirdas-calculator" },
      { name: "Metastatic Prostate Cancer Prognosis Calculator", slug: "metastatic-prostate-cancer-prognosis-calculator" },
      { name: "Protein Creatinine Ratio Calculator", slug: "protein-creatinine-ratio-calculator" },
      { name: "TTKG Calculator", slug: "ttkg-calculator" },
      { name: "URR Calculator", slug: "urr-calculator" }
    ]
  },
  {
    id: "electrolytes-fluids",
    name: "Electrolytes & Fluids",
    calculators: [
      { name: "Anion Gap Calculator", slug: "anion-gap-calculator" },
      { name: "Parkland Formula Calculator", slug: "parkland-formula-calculator" },
      { name: "Acid Base Calculator", slug: "acid-base-calculator" },
      { name: "Arterial Blood pH Calculator", slug: "arterial-blood-ph-calculator" },
      { name: "Bicarbonate Deficit Calculator", slug: "bicarbonate-deficit-calculator" },
      { name: "Corrected Calcium Calculator", slug: "corrected-calcium-calculator" },
      { name: "Corrected Magnesium Calculator", slug: "corrected-magnesium-calculator" },
      { name: "Drip Rate Calculator", slug: "drip-rate-calculator" },
      { name: "Drops Per Minute Calculator", slug: "drops-per-minute-calculator" },
      { name: "Free Water Deficit Calculator", slug: "free-water-deficit-calculator" },
      { name: "IV Flow Rate Calculator", slug: "iv-flow-rate-calculator" },
      { name: "Plasma Osmolality Calculator", slug: "plasma-osmolality-calculator" },
      { name: "Serum Osmolality Calculator", slug: "serum-osmolality-calculator" },
      { name: "Sodium Change Calculator in Hypertriglyceridemia", slug: "sodium-change-hypertriglyceridemia-calculator" },
      { name: "Sodium Correction Calculator", slug: "sodium-correction-calculator" },
      { name: "Sodium Correction Rate Calculator", slug: "sodium-correction-rate-calculator" },
      { name: "Sodium Deficit Calculator", slug: "sodium-deficit-calculator" },
      { name: "Total Body Water Calculator", slug: "total-body-water-calculator" },
      { name: "Urine Anion Gap Calculator", slug: "urine-anion-gap-calculator" },
      { name: "Venous Blood pH Calculator", slug: "venous-blood-ph-calculator" },
      { name: "Water Intake Calculator", slug: "water-intake-calculator" },
      { name: "Winters' Formula Calculator", slug: "winters-formula-calculator" }
    ]
  },
  {
    id: "hematology",
    name: "Hematology",
    calculators: [
      { name: "Blood Volume Calculator", slug: "blood-volume-calculator" },
      { name: "INR Calculator", slug: "inr-calculator" },
      { name: "4T Score Calculator", slug: "4t-score-calculator" },
      { name: "Absolute Eosinophil Count Calculator", slug: "absolute-eosinophil-count-calculator" },
      { name: "Absolute Lymphocyte Count Calculator", slug: "absolute-lymphocyte-count-calculator" },
      { name: "Absolute Reticulocyte Count Calculator", slug: "absolute-reticulocyte-count-calculator" },
      { name: "Age-Adjusted D-dimer Calculator", slug: "age-adjusted-d-dimer-calculator" },
      { name: "Albumin Globulin Ratio Calculator", slug: "albumin-globulin-ratio-calculator" },
      { name: "ANC Calculator", slug: "anc-calculator" },
      { name: "ANC Calculator without Bands", slug: "anc-without-bands-calculator" },
      { name: "Blood Donation Due Date Calculator", slug: "blood-donation-due-date-calculator" },
      { name: "Blood Donor Calculator", slug: "blood-donor-calculator" },
      { name: "Allowable Blood Loss Calculator", slug: "allowable-blood-loss-calculator" },
      { name: "Blood Type Calculator", slug: "blood-type-calculator" },
      { name: "Corrected Reticulocyte Count Calculator", slug: "corrected-reticulocyte-count-calculator" },
      { name: "DIC Syndrome Calculator", slug: "dic-syndrome-calculator" },
      { name: "Diffuse Large B-cell Lymphoma Prognosis Calculator", slug: "dlbcl-prognosis-calculator" },
      { name: "Fresh Frozen Plasma Dose Calculator", slug: "ffp-dose-calculator" },
      { name: "Hematocrit to Hemoglobin Ratio Calculator", slug: "hct-hb-ratio-calculator" },
      { name: "Iron Deficiency Calculator", slug: "iron-deficiency-calculator" },
      { name: "Mentzer Index Calculator", slug: "mentzer-index-calculator" },
      { name: "MIPI Calculator", slug: "mipi-calculator" },
      { name: "mmol/L to mg/dL Calculator", slug: "mmol-to-mgdl-calculator" },
      { name: "NLR Calculator", slug: "nlr-calculator" },
      { name: "Plasma Volume Calculator", slug: "plasma-volume-calculator" },
      { name: "RBC Indices Calculator", slug: "rbc-indices-calculator" },
      { name: "Transferrin Saturation Calculator", slug: "transferrin-saturation-calculator" }
    ]
  },
  {
    id: "pediatric-dosage",
    name: "Pediatric Dosage",
    calculators: [
      { name: "Pediatric Dose Calculator", slug: "pediatric-dose-calculator" },
      { name: "Paracetamol Dosage Calculator", slug: "paracetamol-dosage-calculator" },
      { name: "Amoxicillin Pediatric Dosage Calculator", slug: "amoxicillin-pediatric-dosage-calculator" },
      { name: "Ibuprofen Dosage Calculator", slug: "ibuprofen-dosage-calculator" },
      { name: "Infant Tylenol Dosage Calculator", slug: "infant-tylenol-dosage-calculator" },
      { name: "Pediatric Epinephrine Dose Calculator", slug: "pediatric-epinephrine-dose-calculator" }
    ]
  },
  {
    id: "pulmonary",
    name: "Pulmonary",
    calculators: [
      { name: "Lung Capacity Calculator", slug: "lung-capacity-calculator" },
      { name: "PF Ratio Calculator", slug: "pf-ratio-calculator" },
      { name: "Aa Gradient Calculator", slug: "aa-gradient-calculator" },
      { name: "BODE Index Calculator", slug: "bode-index-calculator" },
      { name: "CURB-65 Calculator", slug: "curb-65-calculator" },
      { name: "Dead Space Calculator", slug: "dead-space-calculator" },
      { name: "Endotracheal Tube Size Calculator", slug: "ett-size-calculator" },
      { name: "FEV1/FVC Ratio Calculator", slug: "fev1-fvc-ratio-calculator" },
      { name: "Light's Criteria Calculator for Pleural Effusion", slug: "lights-criteria-calculator" },
      { name: "Lung Cancer Risk Calculator", slug: "lung-cancer-risk-calculator" },
      { name: "Lung Nodule Growth Rate Calculator", slug: "lung-nodule-growth-rate-calculator" },
      { name: "Mean Airway Pressure Calculator", slug: "mean-airway-pressure-calculator" },
      { name: "Oxygenation Index Calculator", slug: "oxygenation-index-calculator" },
      { name: "Peak Flow Calculator", slug: "peak-flow-calculator" },
      { name: "PSI Calculator", slug: "psi-calculator" },
      { name: "Qp/Qs Calculator", slug: "qp-qs-calculator" },
      { name: "RSBI Calculator", slug: "rsbi-calculator" },
      { name: "Tidal Volume Calculator", slug: "tidal-volume-calculator" },
      { name: "Vital Capacity Calculator", slug: "vital-capacity-calculator" }
    ]
  },
  {
    id: "psychology",
    name: "Psychology",
    calculators: [
      { name: "GAD-7 Calculator", slug: "gad-7-calculator" },
      { name: "PHQ-2 Depression Calculator", slug: "phq-2-depression-calculator" },
      { name: "EPDS Calculator", slug: "epds-calculator" },
      { name: "Happiness Calculator", slug: "happiness-calculator" },
      { name: "SNAP-IV Calculator", slug: "snap-iv-calculator" }
    ]
  },
  {
    id: "emergency-care",
    name: "Emergency Care",
    calculators: [
      { name: "GCS Calculator", slug: "gcs-calculator" },
      { name: "qSOFA Calculator", slug: "qsofa-calculator" },
      { name: "Alvarado Score Calculator", slug: "alvarado-score-calculator" },
      { name: "APACHE II Calculator", slug: "apache-ii-calculator" },
      { name: "Injury Severity Score Calculator", slug: "iss-calculator" },
      { name: "ICH Score Calculator", slug: "ich-score-calculator" },
      { name: "LRINEC Score Calculator", slug: "lrinec-score-calculator" },
      { name: "MEWS Score Calculator", slug: "mews-score-calculator" },
      { name: "NEDOCS Calculator", slug: "nedocs-calculator" },
      { name: "NIH Stroke Scale Calculator", slug: "nihss-calculator" },
      { name: "Revised Trauma Score Calculator", slug: "rts-calculator" },
      { name: "SAPS II Calculator", slug: "saps-ii-calculator" },
      { name: "SCORAD Calculator", slug: "scorad-calculator" },
      { name: "Sepsis Calculator", slug: "sepsis-calculator" },
      { name: "Shock Index Calculator", slug: "shock-index-calculator" },
      { name: "SOFA Score Calculator", slug: "sofa-score-calculator" }
    ]
  },
  {
    id: "army",
    name: "Army & Military Fitness",
    calculators: [
      { name: "Army Body Fat Calculator", slug: "army-body-fat-calculator" },
      { name: "Navy Body Fat Calculator", slug: "navy-body-fat-calculator" },
      { name: "ACFT Calculator", slug: "acft-calculator" },
      { name: "APFT Calculator", slug: "apft-calculator" },
      { name: "AFT Calculator", slug: "aft-calculator" },
      { name: "Air Force PT Calculator", slug: "air-force-pt-calculator" },
      { name: "Navy PRT Calculator", slug: "navy-prt-calculator" }
    ]
  },
  {
    id: "metabolic",
    name: "Metabolic Disorders",
    calculators: [
      { name: "Cholesterol Ratio Calculator", slug: "cholesterol-ratio-calculator" },
      { name: "Cholesterol Units Converter", slug: "cholesterol-units-converter" },
      { name: "LDL Calculator", slug: "ldl-calculator" },
      { name: "VLDL Calculator", slug: "vldl-calculator" },
      { name: "Metabolic Syndrome Calculator", slug: "metabolic-syndrome-calculator" },
      { name: "SAAG Calculator", slug: "saag-calculator" },
      { name: "Gout Diagnosis Calculator", slug: "gout-diagnosis-calculator" }
    ]
  },
  {
    id: "percentile",
    name: "Percentile",
    calculators: [
      { name: "Baby Percentile Calculator", slug: "baby-percentile-calculator" },
      { name: "Birth Weight Percentile Calculator", slug: "birth-weight-percentile-calculator" },
      { name: "BMI Percentile Calculator", slug: "bmi-percentile-calculator" },
      { name: "Height Percentile Calculator", slug: "height-percentile-calculator" },
      { name: "Weight Percentile Calculator", slug: "weight-percentile-calculator" },
      { name: "Fetal Weight Percentile Calculator", slug: "fetal-weight-percentile-calculator" },
      { name: "Head Circumference Percentile Calculator", slug: "head-circumference-percentile-calculator" },
      { name: "IQ Percentile Calculator", slug: "iq-percentile-calculator" }
    ]
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    calculators: [
      { name: "Adjusted Age Calculator", slug: "adjusted-age-calculator" },
      { name: "APGAR Score Calculator", slug: "apgar-score-calculator" },
      { name: "Baby Eye Color Calculator", slug: "baby-eye-color-calculator" },
      { name: "Baby Formula Calculator", slug: "baby-formula-calculator" },
      { name: "Baby's Milk Intake Calculator", slug: "baby-milk-intake-calculator" },
      { name: "Exclusive Pumping Calculator", slug: "exclusive-pumping-calculator" },
      { name: "GIR calculator (Glucose Infusion Rate)", slug: "gir-calculator" },
      { name: "Height Calculator", slug: "height-calculator-child" },
      { name: "Maintenance Fluids Calculator", slug: "maintenance-fluids-calculator" },
      { name: "Newborn Hyperbilirubinemia Assessment Calculator", slug: "newborn-hyperbilirubinemia-calculator" },
      { name: "PECARN Calculator", slug: "pecarn-calculator" },
      { name: "Pediatric Blood Pressure Calculator", slug: "pediatric-blood-pressure-calculator" },
      { name: "Pediatric Blood Transfusion Volume Calculator", slug: "pediatric-blood-transfusion-volume-calculator" },
      { name: "Pediatric Blood Volume Calculator", slug: "pediatric-blood-volume-calculator" },
      { name: "Pediatric GFR Calculator", slug: "pediatric-gfr-calculator" }
    ]
  },
  {
    id: "dosage",
    name: "Dosage",
    calculators: [
      { name: "Adderall Dosage Calculator", slug: "adderall-dosage-calculator" },
      { name: "Aleve Dosage Calculator", slug: "aleve-dosage-calculator" },
      { name: "Benadryl Dosage Calculator", slug: "benadryl-dosage-calculator" },
      { name: "Benzodiazepine Conversion Calculator", slug: "benzo-conversion-calculator" },
      { name: "Carboplatin Calculator", slug: "carboplatin-calculator" },
      { name: "Cefdinir Dose Calculator", slug: "cefdinir-dose-calculator" },
      { name: "Dosage Calculator", slug: "dosage-calculator-general" },
      { name: "Drug Half-Life Calculator", slug: "drug-half-life-calculator" },
      { name: "Fish Oil Calculator", slug: "fish-oil-calculator" },
      { name: "Gabapentin Dosage Calculator", slug: "gabapentin-dosage-calculator" },
      { name: "Hydroxychloroquine Dose Calculator", slug: "hydroxychloroquine-dose-calculator" },
      { name: "Isotretinoin Dose Calculator", slug: "isotretinoin-dose-calculator" },
      { name: "IVIG Dose Calculator", slug: "ivig-dose-calculator" },
      { name: "Levothyroxine Dosage Calculator", slug: "levothyroxine-dosage-calculator" },
      { name: "Lidocaine Dose Calculator", slug: "lidocaine-dose-calculator" },
      { name: "Local Anesthetic Calculator", slug: "local-anesthetic-calculator" },
      { name: "mcg to IU Converter", slug: "mcg-to-iu-converter" },
      { name: "Medicine 3 Times a Day Calculator", slug: "medicine-3-times-a-day-calculator" },
      { name: "Melatonin Dosage Calculator", slug: "melatonin-dosage-calculator" },
      { name: "MME Calculator", slug: "mme-calculator" },
      { name: "Opioid Conversion Calculator", slug: "opioid-conversion-calculator" },
      { name: "Peptide Calculator", slug: "peptide-calculator" },
      { name: "Prescription Refill Calculator", slug: "prescription-refill-calculator" },
      { name: "Steroid Conversion Calculator", slug: "steroid-conversion-calculator" },
      { name: "tPA Calculator", slug: "tpa-calculator" },
      { name: "Tramadol Dosage Calculator", slug: "tramadol-dosage-calculator" },
      { name: "Tylenol Dosage Calculator", slug: "tylenol-dosage-calculator" },
      { name: "Tylenol Overdose Calculator", slug: "tylenol-overdose-calculator" },
      { name: "Warfarin Dosing Calculator", slug: "warfarin-dosing-calculator" }
    ]
  },
  {
    id: "digestive",
    name: "Digestive System",
    calculators: [
      { name: "APRI Calculator", slug: "apri-calculator" },
      { name: "AST/ALT Ratio Calculator", slug: "ast-alt-ratio-calculator" },
      { name: "Child Pugh Calculator", slug: "child-pugh-calculator" },
      { name: "CDAI Calculator", slug: "cdai-calculator" },
      { name: "Maddrey's Discriminant Function Calculator", slug: "maddreys-df-calculator" },
      { name: "FIB-4 Calculator", slug: "fib-4-calculator" },
      { name: "Lille Score Calculator", slug: "lille-score-calculator" },
      { name: "MELD Calculator", slug: "meld-calculator" },
      { name: "NAFLD Fibrosis Score Calculator", slug: "nafld-fibrosis-score-calculator" }
    ]
  },
  {
    id: "epidemiology",
    name: "Epidemiology",
    calculators: [
      { name: "COVID-19 Mortality Risk Calculator", slug: "covid-19-mortality-risk-calculator" },
      { name: "Event Risk Calculator - Coronavirus", slug: "event-risk-calculator-coronavirus" },
      { name: "Denver HIV Risk Score Calculator", slug: "denver-hiv-risk-score-calculator" },
      { name: "Hand Sanitizer Calculator", slug: "hand-sanitizer-calculator" },
      { name: "Incidence Rate Calculator", slug: "incidence-rate-calculator" },
      { name: "Infectious Disease Calculator (SIR)", slug: "sir-model-calculator" },
      { name: "Mask vs. No Mask Calculator", slug: "mask-vs-no-mask-calculator" },
      { name: "Max Vaccine Immunity Calculator", slug: "max-vaccine-immunity-calculator" },
      { name: "Mortality Rate Calculator", slug: "mortality-rate-calculator" },
      { name: "NNT Calculator", slug: "nnt-calculator" },
      { name: "Reopening Calculator - Coronavirus", slug: "reopening-calculator" },
      { name: "Social Distancing Calculator", slug: "social-distancing-calculator" },
      { name: "Swiss Cheese Model Calculator", slug: "swiss-cheese-model-calculator" }
    ]
  },
  {
    id: "radiology",
    name: "Radiology",
    calculators: [
      { name: "BED Calculator", slug: "bed-calculator" },
      { name: "Medical Radiation Calculator", slug: "medical-radiation-calculator" },
      { name: "Radiation Dose Calculator", slug: "radiation-dose-calculator" },
      { name: "TI-RADS Calculator", slug: "ti-rads-calculator" }
    ]
  },
  {
    id: "geriatric",
    name: "Geriatric Medicine",
    calculators: [
      { name: "Alzheimer's Life Expectancy Calculator", slug: "alzheimers-life-expectancy-calculator" },
      { name: "Barthel Index Calculator", slug: "barthel-index-calculator" },
      { name: "BIMS Calculator", slug: "bims-calculator" },
      { name: "Braden Score Calculator", slug: "braden-score-calculator" },
      { name: "Charlson Comorbidity Index Calculator", slug: "charlson-comorbidity-index-calculator" },
      { name: "Frailty Index Calculator", slug: "frailty-index-calculator" },
      { name: "Morse Fall Scale Calculator", slug: "morse-fall-scale-calculator" },
      { name: "Osteoporosis Risk Calculator", slug: "osteoporosis-risk-calculator" },
      { name: "Tinetti Calculator", slug: "tinetti-calculator" }
    ]
  },
  {
    id: "vaccine",
    name: "COVID-19 Vaccine",
    calculators: [
      { name: "Biden’s Vaccine Plan Calculator", slug: "bidens-vaccine-plan-calculator" },
      { name: "Vaccine Efficacy Calculator", slug: "vaccine-efficacy-calculator" },
      { name: "COVID-19 Vaccine Production Calculator", slug: "covid-19-vaccine-production-calculator" },
      { name: "Vaccine Queue Calculator for Australia", slug: "vaccine-queue-calculator-australia" },
      { name: "Vaccine Queue Calculator for India", slug: "vaccine-queue-calculator-india" },
      { name: "Vaccine Queue Calculator for Canada", slug: "vaccine-queue-calculator-canada" },
      { name: "Vaccine Queue Calculator for England", slug: "vaccine-queue-calculator-england" },
      { name: "Vaccine Queue Calculator for Malaysia", slug: "vaccine-queue-calculator-malaysia" },
      { name: "Vaccine Queue Calculator for Ireland", slug: "vaccine-queue-calculator-ireland" },
      { name: "Vaccine Queue Calculator for the Netherlands", slug: "vaccine-queue-calculator-the-netherlands" },
      { name: "Vaccine Queue Calculator for Northern Ireland", slug: "vaccine-queue-calculator-northern-ireland" },
      { name: "Vaccine Queue Calculator for the Philippines", slug: "vaccine-queue-calculator-the-philippines" },
      { name: "Vaccine Queue Calculator for Scotland", slug: "vaccine-queue-calculator-scotland" },
      { name: "Vaccine Queue Calculator for South Africa", slug: "vaccine-queue-calculator-south-africa" },
      { name: "Vaccine Queue Calculator for the UK", slug: "vaccine-queue-calculator-the-uk" },
      { name: "Vaccine Queue Calculator for Wales", slug: "vaccine-queue-calculator-wales" }
    ]
  },
  {
    id: "other",
    name: "Other Health Calculators",
    calculators: [
      { name: "20/20 Vision Calculator", slug: "20-20-vision-calculator" },
      { name: "Aldrete Score Calculator", slug: "aldrete-score-calculator" },
      { name: "BASDAI Score Calculator", slug: "basdai-score-calculator" },
      { name: "Beighton Score Calculator", slug: "beighton-score-calculator" },
      { name: "Berg Balance Test Calculator", slug: "berg-balance-test-calculator" },
      { name: "Hot Car Calculator", slug: "hot-car-calculator" },
      { name: "Centor Score Calculator", slug: "centor-score-calculator" },
      { name: "Dog Walking Benefits Calculator", slug: "dog-walking-benefits-calculator" },
      { name: "DASI Calculator", slug: "dasi-calculator" },
      { name: "EASI Score Calculator", slug: "easi-score-calculator" },
      { name: "Fatigue Severity Scale Calculator", slug: "fatigue-severity-scale-calculator" },
      { name: "Free Testosterone Calculator", slug: "free-testosterone-calculator" },
      { name: "Gut Microbiome Score Calculator", slug: "gut-microbiome-score-calculator" },
      { name: "Noise Pollution Calculator", slug: "noise-pollution-calculator" },
      { name: "Pokémon GO Weight Loss Calculator", slug: "pokemon-go-weight-loss-calculator" },
      { name: "Time Of Death Calculator", slug: "time-of-death-calculator" }
    ]
  }
];
