import { Megaphone, Target, DollarSign, Users, TrendingUp, Share2 } from 'lucide-react';

export const MARKETING_DATA = [
  {
    id: 'advertising',
    name: 'Advertising & Media',
    description: 'Calculate metrics for ad spend, CPM, CPC, reach, and influencer campaigns.',
    icon: Megaphone,
    color: 'bg-red-500',
    calculators: [
      { name: 'Ad Impression Calculator', slug: 'ad-impression-calculator' },
      { name: 'Ad Spend Calculator', slug: 'ad-spend-calculator' },
      { name: 'Campaign Reach Calculator', slug: 'campaign-reach-calculator' },
      { name: 'CPC Calculator', slug: 'cpc-calculator' },
      { name: 'CPM Calculator', slug: 'cpm-calculator' },
      { name: 'CPM vs CPC Comparison Calculator', slug: 'cpm-vs-cpc-calculator' },
      { name: 'CTR Calculator', slug: 'ctr-calculator' },
      { name: 'Influencer Engagement Rate Calculator', slug: 'influencer-engagement-rate-calculator' },
      { name: 'Influencer ROI Calculator', slug: 'influencer-roi-calculator' },
      { name: 'Return on Ad Spend (ROAS) Calculator', slug: 'return-on-ad-spend-calculator' },
      { name: 'Ad Frequency Calculator', slug: 'ad-frequency-calculator' },
      { name: 'Impressions to Reach Calculator', slug: 'impressions-to-reach-calculator' },
      { name: 'PPC Budget Calculator', slug: 'ppc-budget-calculator' },
      { name: 'CPC Bid Calculator', slug: 'cpc-bid-calculator' },
      { name: 'Ad Conversion Value Calculator', slug: 'ad-conversion-value-calculator' },
      { name: 'Podcast Advertising Calculator', slug: 'podcast-advertising-calculator' },
      { name: 'Influencer Cost Calculator', slug: 'influencer-cost-calculator' },
      { name: 'Cost Per Engagement Calculator', slug: 'cost-per-engagement-calculator' },
      { name: 'Impression Share Calculator', slug: 'impression-share-calculator' },
      { name: 'App Install Cost Calculator', slug: 'app-install-cost-calculator' },
      { name: 'Mobile Ad Revenue Calculator', slug: 'mobile-ad-revenue-calculator' },
      { name: 'Google Ads Budget Calculator', slug: 'google-ads-budget-calculator' },
      { name: 'Ad Click Probability Calculator', slug: 'ad-click-probability-calculator' },
      { name: 'Ad Viewability Calculator', slug: 'ad-viewability-calculator' },
      { name: 'Advertising Frequency Calculator', slug: 'advertising-frequency-calculator' },
      { name: 'Digital Ad Cost Calculator', slug: 'digital-ad-cost-calculator' },
      { name: 'Ad Revenue Per Click Calculator', slug: 'ad-revenue-per-click-calculator' },
      { name: 'Ad Placement Performance Calculator', slug: 'ad-placement-performance-calculator' },
      { name: 'Cost Per Thousand Reach Calculator', slug: 'cost-per-thousand-reach-calculator' },
      { name: 'Ad Saturation Calculator', slug: 'ad-saturation-calculator' },
      { name: 'Digital Campaign Reach Calculator', slug: 'digital-campaign-reach-calculator' },
      { name: 'Video Ad Conversion Calculator', slug: 'video-ad-conversion-calculator' },
      { name: 'Ad Placement Frequency Calculator', slug: 'ad-placement-frequency-calculator' },
      { name: 'Ad Conversion Probability Calculator', slug: 'ad-conversion-probability-calculator' },
      { name: 'Ad Budget Allocation Calculator', slug: 'ad-budget-allocation-calculator' }
    ]
  },
  {
    id: 'conversion',
    name: 'Conversion & Funnel',
    description: 'Analyze landing pages, emails, bounce rates, and funnel drop-offs.',
    icon: Target,
    color: 'bg-orange-500',
    calculators: [
      { name: 'Bounce Rate Calculator', slug: 'bounce-rate-calculator' },
      { name: 'Cart Abandonment Calculator', slug: 'cart-abandonment-calculator' },
      { name: 'Conversion Rate Calculator', slug: 'conversion-rate-calculator' },
      { name: 'Email Click Rate Calculator', slug: 'email-click-rate-calculator' },
      { name: 'Email Open Rate Calculator', slug: 'email-open-rate-calculator' },
      { name: 'Funnel Conversion Calculator', slug: 'funnel-conversion-calculator' },
      { name: 'Landing Page Performance Calculator', slug: 'landing-page-performance-calculator' },
      { name: 'Lead Conversion Calculator', slug: 'lead-conversion-calculator' },
      { name: 'Product Demand Forecast Calculator', slug: 'product-demand-forecast-calculator' },
      { name: 'Revenue Per Visitor Calculator', slug: 'revenue-per-visitor-calculator' },
      { name: 'Cost Per Lead (CPL) Calculator', slug: 'cost-per-lead-calculator' },
      { name: 'Funnel Drop-off Calculator', slug: 'funnel-drop-off-calculator' },
      { name: 'Sales Funnel Calculator', slug: 'sales-funnel-calculator' },
      { name: 'Webinar Conversion Calculator', slug: 'webinar-conversion-calculator' },
      { name: 'Email Bounce Rate Calculator', slug: 'email-bounce-rate-calculator' },
      { name: 'Unsubscribe Rate Calculator', slug: 'unsubscribe-rate-calculator' },
      { name: 'Subscriber Growth Calculator', slug: 'subscriber-growth-calculator' },
      { name: 'Conversion Funnel Leakage Calculator', slug: 'conversion-funnel-leakage-calculator' },
      { name: 'Product Conversion Calculator', slug: 'product-conversion-calculator' },
      { name: 'Website Engagement Calculator', slug: 'website-engagement-calculator' },
      { name: 'Landing Page Bounce Calculator', slug: 'landing-page-bounce-calculator' },
      { name: 'Mobile Conversion Rate Calculator', slug: 'mobile-conversion-rate-calculator' },
      { name: 'Push Notification CTR Calculator', slug: 'push-notification-ctr-calculator' },
      { name: 'Conversion Lift Calculator', slug: 'conversion-lift-calculator' },
      { name: 'Shopping Cart Value Calculator', slug: 'shopping-cart-value-calculator' },
      { name: 'Multi-Step Funnel Calculator', slug: 'multi-step-funnel-calculator' },
      { name: 'Lead Qualification Calculator', slug: 'lead-qualification-calculator' },
      { name: 'Traffic-to-Lead Calculator', slug: 'traffic-to-lead-calculator' },
      { name: 'Ecommerce Cart Value Calculator', slug: 'ecommerce-cart-value-calculator' },
      { name: 'Webinar Attendance Rate Calculator', slug: 'webinar-attendance-rate-calculator' },
      { name: 'Shopping Session Duration Calculator', slug: 'shopping-session-duration-calculator' },
      { name: 'Email Deliverability Calculator', slug: 'email-deliverability-calculator' },
      { name: 'Lead-to-Sale Ratio Calculator', slug: 'lead-to-sale-ratio-calculator' },
      { name: 'Store Conversion Calculator', slug: 'store-conversion-calculator' },
      { name: 'Marketing Funnel Velocity Calculator', slug: 'marketing-funnel-velocity-calculator' }
    ]
  },
  {
    id: 'roi',
    name: 'ROI & Profitability',
    description: 'Measure bottom-line impact, break-even points, and sales growth.',
    icon: DollarSign,
    color: 'bg-green-600',
    calculators: [
      { name: 'Affiliate Commission Calculator', slug: 'affiliate-commission-calculator' },
      { name: 'Break-even Analysis Calculator', slug: 'break-even-analysis-calculator' },
      { name: 'Marketing Budget Calculator', slug: 'marketing-budget-calculator' },
      { name: 'Payback Period Calculator', slug: 'payback-period-calculator' },
      { name: 'Profit Margin Calculator', slug: 'profit-margin-calculator' },
      { name: 'Revenue Forecast Calculator', slug: 'revenue-forecast-calculator' },
      { name: 'ROI Calculator', slug: 'roi-calculator' },
      { name: 'Sales Growth Calculator', slug: 'sales-growth-calculator' },
      { name: 'Sales Tax Calculator', slug: 'sales-tax-calculator' },
      { name: 'SEO ROI Calculator', slug: 'seo-roi-calculator' },
      { name: 'Event ROI Calculator', slug: 'event-roi-calculator' },
      { name: 'Marketing Funnel ROI Calculator', slug: 'marketing-funnel-roi-calculator' },
      { name: 'Product Launch ROI Calculator', slug: 'product-launch-roi-calculator' },
      { name: 'Video Marketing ROI Calculator', slug: 'video-marketing-roi-calculator' },
      { name: 'Customer Referral Value Calculator', slug: 'customer-referral-value-calculator' },
      { name: 'Retargeting ROI Calculator', slug: 'retargeting-roi-calculator' },
      { name: 'Ad Placement ROI Calculator', slug: 'ad-placement-roi-calculator' },
      { name: 'Sales Commission Calculator', slug: 'sales-commission-calculator' },
      { name: 'Marketing Efficiency Ratio Calculator', slug: 'marketing-efficiency-ratio-calculator' },
      { name: 'Geo-targeting ROI Calculator', slug: 'geo-targeting-roi-calculator' },
      { name: 'Campaign ROI Forecast Calculator', slug: 'campaign-roi-forecast-calculator' },
      { name: 'Affiliate Revenue Calculator', slug: 'affiliate-revenue-calculator' },
      { name: 'Email Campaign ROI Calculator', slug: 'email-campaign-roi-calculator' },
      { name: 'Loyalty Program ROI Calculator', slug: 'loyalty-program-roi-calculator' },
      { name: 'Seasonal Sales Forecast Calculator', slug: 'seasonal-sales-forecast-calculator' },
      { name: 'Product Recommendation ROI Calculator', slug: 'product-recommendation-roi-calculator' },
      { name: 'Marketing Automation ROI Calculator', slug: 'marketing-automation-roi-calculator' },
      { name: 'Sales Opportunity Calculator', slug: 'sales-opportunity-calculator' },
      { name: 'Traffic Source ROI Calculator', slug: 'traffic-source-roi-calculator' },
      { name: 'Campaign Profitability Calculator', slug: 'campaign-profitability-calculator' },
      { name: 'Ecommerce Conversion Value Calculator', slug: 'ecommerce-conversion-value-calculator' },
      { name: 'Sales Pipeline Calculator', slug: 'sales-pipeline-calculator' },
      { name: 'Paid Search ROI Calculator', slug: 'paid-search-roi-calculator' },
      { name: 'Campaign Duration Calculator', slug: 'campaign-duration-calculator' },
      { name: 'Customer Referral ROI Calculator', slug: 'customer-referral-roi-calculator' },
      { name: 'Customer Acquisition Forecast Calculator', slug: 'customer-acquisition-forecast-calculator' },
      { name: 'Cost Per Acquisition Forecast Calculator', slug: 'cost-per-acquisition-forecast-calculator' },
      { name: 'Campaign Success Probability Calculator', slug: 'campaign-success-probability-calculator' },
      { name: 'Seasonal Marketing ROI Calculator', slug: 'seasonal-marketing-roi-calculator' }
    ]
  },
  {
    id: 'customer',
    name: 'Customer Metrics',
    description: 'Track churn, retention, NPS, CSAT, and acquisition costs.',
    icon: Users,
    color: 'bg-blue-600',
    calculators: [
      { name: 'Audience Growth Calculator', slug: 'audience-growth-calculator' },
      { name: 'Brand Awareness Calculator', slug: 'brand-awareness-calculator' },
      { name: 'Churn Rate Calculator', slug: 'churn-rate-calculator' },
      { name: 'CSAT Score Calculator', slug: 'csat-calculator' },
      { name: 'Customer Acquisition Cost (CAC) Calculator', slug: 'cac-calculator' },
      { name: 'Customer Lifetime Value (CLV) Calculator', slug: 'clv-calculator' },
      { name: 'Net Promoter Score (NPS) Calculator', slug: 'nps-calculator' },
      { name: 'Referral Rate Calculator', slug: 'referral-rate-calculator' },
      { name: 'Retention Rate Calculator', slug: 'retention-rate-calculator' },
      { name: 'Social Media Engagement Calculator', slug: 'social-media-engagement-calculator' },
      { name: 'Customer Loyalty Calculator', slug: 'customer-loyalty-calculator' },
      { name: 'Customer Segmentation Calculator', slug: 'customer-segmentation-calculator' },
      { name: 'Brand Recall Calculator', slug: 'brand-recall-calculator' },
      { name: 'Brand Sentiment Calculator', slug: 'brand-sentiment-calculator' },
      { name: 'Customer Journey Calculator', slug: 'customer-journey-calculator' },
      { name: 'Customer Persona Calculator', slug: 'customer-persona-calculator' },
      { name: 'Brand Consistency Calculator', slug: 'brand-consistency-calculator' },
      { name: 'Customer Reactivation Calculator', slug: 'customer-reactivation-calculator' },
      { name: 'Product Popularity Calculator', slug: 'product-popularity-calculator' },
      { name: 'Customer Retention Value Calculator', slug: 'customer-retention-value-calculator' },
      { name: 'Brand Trust Score Calculator', slug: 'brand-trust-score-calculator' },
      { name: 'Customer Win-back Calculator', slug: 'customer-win-back-calculator' },
      { name: 'Customer Intent Score Calculator', slug: 'customer-intent-score-calculator' },
      { name: 'Repeat Purchase Rate Calculator', slug: 'repeat-purchase-rate-calculator' },
      { name: 'Customer Engagement Score Calculator', slug: 'customer-engagement-score-calculator' },
      { name: 'Customer Loyalty Index Calculator', slug: 'customer-loyalty-index-calculator' },
      { name: 'User Activation Calculator', slug: 'user-activation-calculator' },
      { name: 'Product Review Score Calculator', slug: 'product-review-score-calculator' },
      { name: 'Customer Return Frequency Calculator', slug: 'customer-return-frequency-calculator' },
      { name: 'Shopping Behavior Calculator', slug: 'shopping-behavior-calculator' },
      { name: 'Customer Engagement Forecast Calculator', slug: 'customer-engagement-forecast-calculator' }
    ]
  },
  {
    id: 'strategy',
    name: 'Strategy & Growth',
    description: 'Calculate ARR, MRR, market share, and pricing strategies.',
    icon: TrendingUp,
    color: 'bg-purple-600',
    calculators: [
      { name: 'ARR Calculator', slug: 'arr-calculator' },
      { name: 'Average Order Value (AOV) Calculator', slug: 'aov-calculator' },
      { name: 'Discount Percentage Calculator', slug: 'discount-percentage-calculator' },
      { name: 'Keyword Density Calculator', slug: 'keyword-density-calculator' },
      { name: 'Market Share Calculator', slug: 'market-share-calculator' },
      { name: 'Pricing Strategy Calculator', slug: 'pricing-strategy-calculator' },
      { name: 'SaaS MRR Calculator', slug: 'saas-mrr-calculator' },
      { name: 'Subscription Revenue Calculator', slug: 'subscription-revenue-calculator' },
      { name: 'Viral Coefficient Calculator', slug: 'viral-coefficient-calculator' },
      { name: 'Brand Equity Calculator', slug: 'brand-equity-calculator' },
      { name: 'Product Pricing Calculator', slug: 'product-pricing-calculator' },
      { name: 'Organic Traffic Growth Calculator', slug: 'organic-traffic-growth-calculator' },
      { name: 'SEO Backlink Value Calculator', slug: 'seo-backlink-value-calculator' },
      { name: 'Keyword Difficulty Calculator', slug: 'keyword-difficulty-calculator' },
      { name: 'Store Footfall Calculator', slug: 'store-footfall-calculator' },
      { name: 'E-commerce Revenue Calculator', slug: 'ecommerce-revenue-calculator' },
      { name: 'Upsell Revenue Calculator', slug: 'upsell-revenue-calculator' },
      { name: 'Cross-sell Revenue Calculator', slug: 'cross-sell-revenue-calculator' },
      { name: 'Competitor Analysis Calculator', slug: 'competitor-analysis-calculator' },
      { name: 'Dynamic Pricing Calculator', slug: 'dynamic-pricing-calculator' },
      { name: 'Digital Marketing Score Calculator', slug: 'digital-marketing-score-calculator' },
      { name: 'Viral Marketing Reach Calculator', slug: 'viral-marketing-reach-calculator' },
      { name: 'Search Volume Calculator', slug: 'search-volume-calculator' },
      { name: 'Market Penetration Calculator', slug: 'market-penetration-calculator' },
      { name: 'Multi-Channel Attribution Calculator', slug: 'multi-channel-attribution-calculator' },
      { name: 'Ecommerce Growth Calculator', slug: 'ecommerce-growth-calculator' },
      { name: 'Competitor Pricing Calculator', slug: 'competitor-pricing-calculator' },
      { name: 'Search Ranking Value Calculator', slug: 'search-ranking-value-calculator' },
      { name: 'Marketing KPI Calculator', slug: 'marketing-kpi-calculator' },
      { name: 'Marketing Productivity Calculator', slug: 'marketing-productivity-calculator' },
      { name: 'Brand Growth Calculator', slug: 'brand-growth-calculator' },
      { name: 'Marketing Spend Efficiency Calculator', slug: 'marketing-spend-efficiency-calculator' },
      { name: 'Market Opportunity Calculator', slug: 'market-opportunity-calculator' },
      { name: 'Brand Exposure Calculator', slug: 'brand-exposure-calculator' },
      { name: 'Organic Search Performance Calculator', slug: 'organic-search-performance-calculator' },
      { name: 'Brand Positioning Calculator', slug: 'brand-positioning-calculator' },
      { name: 'Search Engine Visibility Calculator', slug: 'search-engine-visibility-calculator' },
      { name: 'Sales Velocity Calculator', slug: 'sales-velocity-calculator' },
      { name: 'Product Awareness Calculator', slug: 'product-awareness-calculator' },
      { name: 'Digital Presence Score Calculator', slug: 'digital-presence-score-calculator' },
      { name: 'Revenue Attribution Calculator', slug: 'revenue-attribution-calculator' },
      { name: 'Product Demand Trend Calculator', slug: 'product-demand-trend-calculator' }
    ]
  },
  {
    id: 'social',
    name: 'Social Media & Platforms',
    description: 'Calculate engagement, reach, and monetization across social platforms.',
    icon: Share2,
    color: 'bg-pink-500',
    calculators: [
      { name: 'Engagement Per Post Calculator', slug: 'engagement-per-post-calculator' },
      { name: 'YouTube CPM Earnings Calculator', slug: 'youtube-cpm-earnings-calculator' },
      { name: 'TikTok Engagement Calculator', slug: 'tiktok-engagement-calculator' },
      { name: 'Instagram Reach Calculator', slug: 'instagram-reach-calculator' },
      { name: 'Facebook Ad ROI Calculator', slug: 'facebook-ad-roi-calculator' },
      { name: 'LinkedIn Campaign Calculator', slug: 'linkedin-campaign-calculator' },
      { name: 'Pinterest Traffic Calculator', slug: 'pinterest-traffic-calculator' },
      { name: 'Twitter Engagement Rate Calculator', slug: 'twitter-engagement-rate-calculator' },
      { name: 'Meta Ads Performance Calculator', slug: 'meta-ads-performance-calculator' },
      { name: 'Social Share Rate Calculator', slug: 'social-share-rate-calculator' },
      { name: 'Influencer Campaign Reach Calculator', slug: 'influencer-campaign-reach-calculator' },
      { name: 'Audience Retention Calculator', slug: 'audience-retention-calculator' },
      { name: 'Engagement-to-Sales Calculator', slug: 'engagement-to-sales-calculator' },
      { name: 'Video Watch Time Calculator', slug: 'video-watch-time-calculator' },
      { name: 'Social Proof Calculator', slug: 'social-proof-calculator' },
      { name: 'Social Media Growth Rate Calculator', slug: 'social-media-growth-rate-calculator' },
      { name: 'Engagement Quality Calculator', slug: 'engagement-quality-calculator' },
      { name: 'Viral Reach Multiplier Calculator', slug: 'viral-reach-multiplier-calculator' }
    ]
  }
];
