export const MATH_DATA = [
  {
    id: "percentages",
    name: "Percentages",
    calculators: [
      { name: "Average Percentage Calculator", slug: "average-percentage-calculator" },
      { name: "Fraction to Percent Calculator", slug: "fraction-to-percent-calculator" },
      { name: "Decimal to Percent Converter", slug: "decimal-to-percent-converter" },
      { name: "Doubling Time Calculator", slug: "doubling-time-calculator" },
      { name: "Percentage Calculator", slug: "percentage-calculator" },
      { name: "Percentage Change Calculator", slug: "percentage-change-calculator" },
      { name: "Percentage Decrease Calculator", slug: "percentage-decrease-calculator" },
      { name: "Percentage Difference Calculator", slug: "percentage-difference-calculator" },
      { name: "Percentage Increase Calculator", slug: "percentage-increase-calculator" },
      { name: "Percentage Increase Classic", slug: "percentage-increase-classic" },
      { name: "Percentage of a Percentage Calculator", slug: "percentage-of-a-percentage-calculator" },
      { name: "Percentage Point Calculator", slug: "percentage-point-calculator" },
      { name: "Percent Error Calculator", slug: "percent-error-calculator" },
      { name: "Time Percentage Calculator", slug: "time-percentage-calculator" },
      { name: "Percent to Goal Calculator", slug: "percent-to-goal-calculator" },
      { name: "Relative Change Calculator", slug: "relative-change-calculator" },
      { name: "Slope Percentage Calculator", slug: "slope-percentage-calculator" }
    ]
  },
  {
    id: "algebra",
    name: "Algebra",
    calculators: [
      { name: "Absolute Value Equation Calculator", slug: "absolute-value-equation-calculator" },
      { name: "Absolute Value Inequalities Calculator", slug: "absolute-value-inequalities-calculator" },
      { name: "Adding and Subtracting Polynomials Calculator", slug: "adding-and-subtracting-polynomials-calculator" },
      { name: "Bessel Function Calculator", slug: "bessel-function-calculator" },
      { name: "Binomial Coefficient Calculator", slug: "binomial-coefficient-calculator" },
      { name: "Box Method Calculator", slug: "box-method-calculator" },
      { name: "Completing the Square Calculator", slug: "completing-the-square-calculator" },
      { name: "Complex Conjugate Calculator", slug: "complex-conjugate-calculator" },
      { name: "Complex Number Calculator", slug: "complex-number-calculator" },
      { name: "Complex Root Calculator", slug: "complex-root-calculator" },
      { name: "Cubic Equation Calculator", slug: "cubic-equation-calculator" },
      { name: "Descartes' Rule of Signs Calculator", slug: "descartes-rule-of-signs-calculator" },
      { name: "Diamond Problem Calculator", slug: "diamond-problem-calculator" },
      { name: "Direct Variation Calculator", slug: "direct-variation-calculator" },
      { name: "Discriminant Calculator", slug: "discriminant-calculator" },
      { name: "Elimination Method Calculator", slug: "elimination-method-calculator" },
      { name: "Error Function Calculator", slug: "error-function-calculator" },
      { name: "Factoring Trinomials Calculator", slug: "factoring-trinomials-calculator" },
      { name: "FOIL Calculator", slug: "foil-calculator" },
      { name: "Gamma Function Calculator", slug: "gamma-function-calculator" },
      { name: "Generic Rectangle Calculator", slug: "generic-rectangle-calculator" },
      { name: "Graphing Inequalities on a Number Line Calculator", slug: "graphing-inequalities-on-a-number-line-calculator" },
      { name: "Graphing Quadratic Inequalities Calculator", slug: "graphing-quadratic-inequalities-calculator" },
      { name: "Hyperbolic Functions Calculator", slug: "hyperbolic-functions-calculator" },
      { name: "Inequality to Interval Notation Calculator", slug: "inequality-to-interval-notation-calculator" },
      { name: "Interval Notation Calculator", slug: "interval-notation-calculator" },
      { name: "Inverse Variation Calculator", slug: "inverse-variation-calculator" },
      { name: "Multiplying Binomials Calculator", slug: "multiplying-binomials-calculator" },
      { name: "Multiplying Polynomials Calculator", slug: "multiplying-polynomials-calculator" },
      { name: "Partial Fraction Decomposition Calculator", slug: "partial-fraction-decomposition-calculator" },
      { name: "Perfect Square Trinomial Calculator", slug: "perfect-square-trinomial-calculator" },
      { name: "Polynomial Division Calculator", slug: "polynomial-division-calculator" },
      { name: "Power Set Calculator", slug: "power-set-calculator" },
      { name: "Quadratic Formula Calculator", slug: "quadratic-formula-calculator" },
      { name: "Quaternion Calculator", slug: "quaternion-calculator" },
      { name: "Rational Zeros Calculator", slug: "rational-zeros-calculator" },
      { name: "Square of a Binomial Calculator", slug: "square-of-a-binomial-calculator" },
      { name: "Subset Calculator", slug: "subset-calculator" },
      { name: "Substitution Method Calculator", slug: "substitution-method-calculator" },
      { name: "Synthetic Division Calculator", slug: "synthetic-division-calculator" },
      { name: "System of Equations Calculator", slug: "system-of-equations-calculator" },
      { name: "Truth Table Generator", slug: "truth-table-generator" },
      { name: "Union and Intersection Calculator", slug: "union-and-intersection-calculator" }
    ]
  },
  {
    id: "arithmetic",
    name: "Arithmetic",
    calculators: [
      { name: "Absolute Change Calculator", slug: "absolute-change-calculator" },
      { name: "Absolute Value Calculator", slug: "absolute-value-calculator" },
      { name: "Adding and Subtracting Fractions Calculator", slug: "adding-and-subtracting-fractions-calculator" },
      { name: "Addition Calculator", slug: "addition-calculator" },
      { name: "Associative Property Calculator", slug: "associative-property-calculator" },
      { name: "Average Calculator", slug: "average-calculator" },
      { name: "Ceiling Function Calculator", slug: "ceiling-function-calculator" },
      { name: "Chinese Remainder Theorem Calculator", slug: "chinese-remainder-theorem-calculator" },
      { name: "Compatible Numbers Calculator", slug: "compatible-numbers-calculator" },
      { name: "Consecutive Integers Calculator", slug: "consecutive-integers-calculator" },
      { name: "Cross Multiplication Calculator", slug: "cross-multiplication-calculator" },
      { name: "Cube Root Calculator", slug: "cube-root-calculator" },
      { name: "Decimal Calculator", slug: "decimal-calculator" },
      { name: "Digital Root Calculator", slug: "digital-root-calculator" },
      { name: "Distributive Property Calculator", slug: "distributive-property-calculator" },
      { name: "Divisibility Test Calculator", slug: "divisibility-test-calculator" },
      { name: "Division Calculator", slug: "division-calculator" },
      { name: "Egyptian Fractions Calculator", slug: "egyptian-fractions-calculator" },
      { name: "Expanded Form Calculator", slug: "expanded-form-calculator" },
      { name: "Factor Calculator", slug: "factor-calculator" },
      { name: "Factorial Calculator", slug: "factorial-calculator" },
      { name: "Fermat's Little Theorem Calculator", slug: "fermat-s-little-theorem-calculator" },
      { name: "Floor Division Calculator", slug: "floor-division-calculator" },
      { name: "Floor Function Calculator", slug: "floor-function-calculator" },
      { name: "Fundamental Counting Principle Calculator", slug: "fundamental-counting-principle-calculator" },
      { name: "GCF Calculator – Greatest Common Factor", slug: "gcf-calculator-greatest-common-factor" },
      { name: "GCF and LCM Calculator", slug: "gcf-and-lcm-calculator" },
      { name: "Geometric Mean Calculator", slug: "geometric-mean-calculator" },
      { name: "Greater Than Or Less Than Calculator", slug: "greater-than-or-less-than-calculator" },
      { name: "Harmonic Mean Calculator", slug: "harmonic-mean-calculator" },
      { name: "Integer Calculator", slug: "integer-calculator" },
      { name: "Inverse Modulo Calculator", slug: "inverse-modulo-calculator" },
      { name: "LCM Calculator — Least Common Multiple", slug: "lcm-calculator-least-common-multiple" },
      { name: "Long Addition Calculator", slug: "long-addition-calculator" },
      { name: "Long Multiplication Calculator", slug: "long-multiplication-calculator" },
      { name: "Long Subtraction Calculator", slug: "long-subtraction-calculator" },
      { name: "Magic Square Calculator", slug: "magic-square-calculator" },
      { name: "Mean Calculator", slug: "mean-calculator" },
      { name: "Modulo Calculator", slug: "modulo-calculator" },
      { name: "Multiplication Calculator", slug: "multiplication-calculator" },
      { name: "Multiplicative Inverse Calculator", slug: "multiplicative-inverse-calculator" },
      { name: "Multiplicative Inverse Modulo Calculator", slug: "multiplicative-inverse-modulo-calculator" },
      { name: "Order of Magnitude Calculator", slug: "order-of-magnitude-calculator" },
      { name: "Partial Products Calculator", slug: "partial-products-calculator" },
      { name: "Perfect Cube Calculator", slug: "perfect-cube-calculator" },
      { name: "Perfect Square Calculator", slug: "perfect-square-calculator" },
      { name: "Pi Experiments Calculator", slug: "pi-experiments-calculator" },
      { name: "Place Value Calculator", slug: "place-value-calculator" },
      { name: "Polish Notation Converter", slug: "polish-notation-converter" },
      { name: "Power Mod Calculator", slug: "power-mod-calculator" },
      { name: "Powers of i Calculator", slug: "powers-of-i-calculator" },
      { name: "Prime Factorization Calculator", slug: "prime-factorization-calculator" },
      { name: "Prime Number Calculator", slug: "prime-number-calculator" },
      { name: "Quotient Calculator", slug: "quotient-calculator" },
      { name: "Radical Calculator", slug: "radical-calculator" },
      { name: "Rationalize Denominator Calculator", slug: "rationalize-denominator-calculator" },
      { name: "Reciprocal Calculator", slug: "reciprocal-calculator" },
      { name: "Relatively Prime Calculator", slug: "relatively-prime-calculator" },
      { name: "Remainder Calculator", slug: "remainder-calculator" },
      { name: "Reverse FOIL Calculator", slug: "reverse-foil-calculator" },
      { name: "Root Calculator", slug: "root-calculator" },
      { name: "Root Mean Square Calculator", slug: "root-mean-square-calculator" },
      { name: "Rounding Calculator", slug: "rounding-calculator" },
      { name: "Round to the Nearest Thousand Calculator", slug: "round-to-the-nearest-thousand-calculator" },
      { name: "Scientific Notation Calculator", slug: "scientific-notation-calculator" },
      { name: "Set Builder Calculator", slug: "set-builder-calculator" },
      { name: "Significant Figures Calculator – Sig Fig", slug: "significant-figures-calculator-sig-fig" },
      { name: "Simplify Cube Root Calculator", slug: "simplify-cube-root-calculator" },
      { name: "Simplifying Radicals Calculator", slug: "simplifying-radicals-calculator" },
      { name: "Square Root Calculator", slug: "square-root-calculator" },
      { name: "Standard Form Calculator", slug: "standard-form-calculator" },
      { name: "Subtracting Fractions Calculator", slug: "subtracting-fractions-calculator" },
      { name: "Subtraction Calculator", slug: "subtraction-calculator" },
      { name: "Digit Sum Calculator", slug: "digit-sum-calculator" },
      { name: "Sum of Products Calculator", slug: "sum-of-products-calculator" },
      { name: "Terminating Decimals Calculator", slug: "terminating-decimals-calculator" },
      { name: "Triangular Numbers Calculator", slug: "triangular-numbers-calculator" },
      { name: "Weighted Average Calculator", slug: "weighted-average-calculator" }
    ]
  },
  {
    id: "coordinate-geometry",
    name: "Coordinate Geometry",
    calculators: [
      { name: "Average Rate of Change Calculator", slug: "average-rate-of-change-calculator" },
      { name: "Bilinear Interpolation Calculator", slug: "bilinear-interpolation-calculator" },
      { name: "Catenary Curve Calculator", slug: "catenary-curve-calculator" },
      { name: "Coordinate Grid Calculator", slug: "coordinate-grid-calculator" },
      { name: "Cosine Similarity Calculator", slug: "cosine-similarity-calculator" },
      { name: "Cross Product Calculator", slug: "cross-product-calculator" },
      { name: "Cylindrical Coordinates Calculator", slug: "cylindrical-coordinates-calculator" },
      { name: "Direction of the Vector Calculator", slug: "direction-of-the-vector-calculator" },
      { name: "Distance Formula Calculator", slug: "distance-formula-calculator" },
      { name: "Distance from Point to Plane Calculator", slug: "distance-from-point-to-plane-calculator" },
      { name: "Dot Product Calculator", slug: "dot-product-calculator" },
      { name: "Endpoint Calculator", slug: "endpoint-calculator" },
      { name: "Equation of a Sphere Calculator", slug: "equation-of-a-sphere-calculator" },
      { name: "Gradient Calculator", slug: "gradient-calculator" },
      { name: "Intersection of Two Lines Calculator", slug: "intersection-of-two-lines-calculator" },
      { name: "Irregular Polygon Area Calculator", slug: "irregular-polygon-area-calculator" },
      { name: "Latus Rectum Calculator", slug: "latus-rectum-calculator" },
      { name: "Least Squares Regression Line Calculator", slug: "least-squares-regression-line-calculator" },
      { name: "Linear Interpolation Calculator", slug: "linear-interpolation-calculator" },
      { name: "Line Equation from Two Points Calculator", slug: "line-equation-from-two-points-calculator" },
      { name: "Line of Intersection of Two Planes Calculator", slug: "line-of-intersection-of-two-planes-calculator" },
      { name: "Manhattan Distance Calculator", slug: "manhattan-distance-calculator" },
      { name: "Midpoint Calculator", slug: "midpoint-calculator" },
      { name: "Parabola Calculator", slug: "parabola-calculator" },
      { name: "Parallel Line Calculator", slug: "parallel-line-calculator" },
      { name: "Perpendicular Line Calculator", slug: "perpendicular-line-calculator" },
      { name: "Point Slope Form Calculator", slug: "point-slope-form-calculator" },
      { name: "Polar Coordinates Calculator", slug: "polar-coordinates-calculator" },
      { name: "Polynomial Graphing Calculator", slug: "polynomial-graphing-calculator" },
      { name: "Ratios of Directed Line Segments Calculator", slug: "ratios-of-directed-line-segments-calculator" },
      { name: "Rise Over Run Calculator", slug: "rise-over-run-calculator" },
      { name: "Rotation Calculator", slug: "rotation-calculator" },
      { name: "Scatter Plot Calculator", slug: "scatter-plot-calculator" },
      { name: "Slope Calculator", slug: "slope-calculator" },
      { name: "Slope Intercept Form Calculator", slug: "slope-intercept-form-calculator" },
      { name: "Spherical Coordinates Calculator", slug: "spherical-coordinates-calculator" },
      { name: "Standard Form to Slope Intercept Form Calculator", slug: "standard-form-to-slope-intercept-form-calculator" },
      { name: "Three-Dimensional Distance Calculator", slug: "three-dimensional-distance-calculator" },
      { name: "Triangulation Calculator", slug: "triangulation-calculator" },
      { name: "Unit Vector Calculator", slug: "unit-vector-calculator" },
      { name: "Vector Calculator", slug: "vector-calculator" },
      { name: "Vector Addition Calculator", slug: "vector-addition-calculator" },
      { name: "Vector Magnitude Calculator", slug: "vector-magnitude-calculator" },
      { name: "Vector Projection Calculator", slug: "vector-projection-calculator" },
      { name: "Vertex Form Calculator", slug: "vertex-form-calculator" },
      { name: "Volume of a Parallelepiped Calculator", slug: "volume-of-a-parallelepiped-calculator" },
      { name: "y Intercept Calculator", slug: "y-intercept-calculator" }
    ]
  },
  {
    id: "fractions",
    name: "Fractions",
    calculators: [
      { name: "Adding Fractions Calculator", slug: "adding-fractions-calculator" },
      { name: "Comparing Fractions Calculator", slug: "comparing-fractions-calculator" },
      { name: "Decimal to Fraction Calculator", slug: "decimal-to-fraction-calculator" },
      { name: "Dividing Fractions Calculator", slug: "dividing-fractions-calculator" },
      { name: "Equivalent Fractions Calculator", slug: "equivalent-fractions-calculator" },
      { name: "Fraction Calculator", slug: "fraction-calculator" },
      { name: "Fraction Exponent Calculator", slug: "fraction-exponent-calculator" },
      { name: "Fraction To Decimal Converter", slug: "fraction-to-decimal-converter" },
      { name: "Golden Ratio Calculator", slug: "golden-ratio-calculator" },
      { name: "Improper Fraction to Mixed Number Calculator", slug: "improper-fraction-to-mixed-number-calculator" },
      { name: "LCD Calculator - Least Common Denominator", slug: "lcd-calculator-least-common-denominator" },
      { name: "Lowest Term Calculator", slug: "lowest-term-calculator" },
      { name: "Mixed Number Calculator", slug: "mixed-number-calculator" },
      { name: "Mixed Number to Improper Fraction Calculator", slug: "mixed-number-to-improper-fraction-calculator" },
      { name: "Multiplying Fractions Calculator", slug: "multiplying-fractions-calculator" },
      { name: "Proportion Calculator", slug: "proportion-calculator" },
      { name: "Ratio Calculator", slug: "ratio-calculator" },
      { name: "Simplify Fractions Calculator", slug: "simplify-fractions-calculator" },
      { name: "Unit Rate Calculator", slug: "unit-rate-calculator" }
    ]
  },
  {
    id: "linear-algebra",
    name: "Linear Algebra",
    calculators: [
      { name: "Adjoint Matrix Calculator", slug: "adjoint-matrix-calculator" },
      { name: "Characteristic Polynomial Calculator", slug: "characteristic-polynomial-calculator" },
      { name: "Cholesky Decomposition Calculator", slug: "cholesky-decomposition-calculator" },
      { name: "Cofactor Expansion Calculator", slug: "cofactor-expansion-calculator" },
      { name: "Cofactor Matrix Calculator", slug: "cofactor-matrix-calculator" },
      { name: "Column Space Calculator", slug: "column-space-calculator" },
      { name: "Condition Number Calculator", slug: "condition-number-calculator" },
      { name: "Corner Point Calculator", slug: "corner-point-calculator" },
      { name: "Cramer's Rule Calculator", slug: "cramer-s-rule-calculator" },
      { name: "Diagonalize Matrix Calculator", slug: "diagonalize-matrix-calculator" },
      { name: "Eigenvalue and Eigenvector Calculator", slug: "eigenvalue-and-eigenvector-calculator" },
      { name: "Gauss-Jordan Elimination Calculator", slug: "gauss-jordan-elimination-calculator" },
      { name: "Gram-Schmidt Calculator", slug: "gram-schmidt-calculator" },
      { name: "Hadamard Product Calculator", slug: "hadamard-product-calculator" },
      { name: "Inverse Matrix Calculator", slug: "inverse-matrix-calculator" },
      { name: "Linear Combination Calculator", slug: "linear-combination-calculator" },
      { name: "Linear Independence Calculator", slug: "linear-independence-calculator" },
      { name: "LU Decomposition Calculator", slug: "lu-decomposition-calculator" },
      { name: "Matrix Calculator", slug: "matrix-calculator" },
      { name: "Matrix Addition and Subtraction Calculator", slug: "matrix-addition-and-subtraction-calculator" },
      { name: "Matrix by Scalar Calculator", slug: "matrix-by-scalar-calculator" },
      { name: "Matrix Determinant Calculator", slug: "matrix-determinant-calculator" },
      { name: "Matrix Multiplication Calculator", slug: "matrix-multiplication-calculator" },
      { name: "Matrix Norm Calculator", slug: "matrix-norm-calculator" },
      { name: "Matrix Power Calculator", slug: "matrix-power-calculator" },
      { name: "Matrix Rank Calculator", slug: "matrix-rank-calculator" },
      { name: "Matrix Trace Calculator", slug: "matrix-trace-calculator" },
      { name: "Matrix Transpose Calculator", slug: "matrix-transpose-calculator" },
      { name: "Null Space Calculator", slug: "null-space-calculator" },
      { name: "Polar Decomposition Calculator", slug: "polar-decomposition-calculator" },
      { name: "Pseudoinverse Calculator", slug: "pseudoinverse-calculator" },
      { name: "QR Decomposition Calculator", slug: "qr-decomposition-calculator" },
      { name: "(Reduced) Row Echelon Form Calculator", slug: "reduced-row-echelon-form-calculator" },
      { name: "Singular Values Calculator", slug: "singular-values-calculator" },
      { name: "SVD Calculator", slug: "svd-calculator" },
      { name: "Tensor Product Calculator", slug: "tensor-product-calculator" }
    ]
  },
  {
    id: "trigonometry",
    name: "Trigonometry",
    calculators: [
      { name: "Arccos Calculator (Inverse Cosine)", slug: "arccos-calculator-inverse-cosine" },
      { name: "Arcsin Calculator (Inverse Sine)", slug: "arcsin-calculator-inverse-sine" },
      { name: "Arctan Calculator (Inverse Tangent)", slug: "arctan-calculator-inverse-tangent" },
      { name: "Cofunction Calculator", slug: "cofunction-calculator" },
      { name: "Cosecant Calculator", slug: "cosecant-calculator" },
      { name: "Cosine Calculator", slug: "cosine-calculator" },
      { name: "Cotangent Calculator", slug: "cotangent-calculator" },
      { name: "Double Angle Formula Calculator", slug: "double-angle-formula-calculator" },
      { name: "Half Angle Calculator", slug: "half-angle-calculator" },
      { name: "Inverse Trigonometric Functions Calculator", slug: "inverse-trigonometric-functions-calculator" },
      { name: "Law of Cosines Calculator", slug: "law-of-cosines-calculator" },
      { name: "Law of Sines Calculator", slug: "law-of-sines-calculator" },
      { name: "Phase Shift Calculator", slug: "phase-shift-calculator" },
      { name: "Power Reducing Calculator", slug: "power-reducing-calculator" },
      { name: "Quiz: Right Triangle Side and Angle Calculator", slug: "quiz-right-triangle-side-and-angle-calculator" },
      { name: "Quiz: Trigonometry Calculator", slug: "quiz-trigonometry-calculator" },
      { name: "Secant Calculator", slug: "secant-calculator" },
      { name: "Sine Calculator", slug: "sine-calculator" },
      { name: "Sum and Difference Identities Calculator", slug: "sum-and-difference-identities-calculator" },
      { name: "Tangent Calculator", slug: "tangent-calculator" },
      { name: "Trig Identities Calculator", slug: "trig-identities-calculator" },
      { name: "Trigonometric Functions Calculator", slug: "trigonometric-functions-calculator" },
      { name: "Trigonometry Calculator", slug: "trigonometry-calculator" },
      { name: "Unit Circle Calculator", slug: "unit-circle-calculator" }
    ]
  },
  {
    id: "2d-geometry",
    name: "2D Geometry",
    calculators: [
      { name: "Area Calculator", slug: "area-calculator" },
      { name: "Area of a Rectangle Calculator", slug: "area-of-a-rectangle-calculator" },
      { name: "Area of Crescent Calculator", slug: "area-of-crescent-calculator" },
      { name: "Center of Mass Calculator", slug: "center-of-mass-calculator" },
      { name: "Centroid Calculator", slug: "centroid-calculator" },
      { name: "Chord Length Calculator", slug: "chord-length-calculator" },
      { name: "Conic Sections Calculator", slug: "conic-sections-calculator" },
      { name: "Cross-Sectional Area Calculator", slug: "cross-sectional-area-calculator" },
      { name: "Cycloid Calculator", slug: "cycloid-calculator" },
      { name: "Ellipse Calculator", slug: "ellipse-calculator" },
      { name: "Golden Rectangle Calculator", slug: "golden-rectangle-calculator" },
      { name: "Hexagon Calculator", slug: "hexagon-calculator" },
      { name: "Möbius Strip Calculator", slug: "m-bius-strip-calculator" },
      { name: "Moment of Inertia Calculator", slug: "moment-of-inertia-calculator" },
      { name: "Octagon Calculator", slug: "octagon-calculator" },
      { name: "Orthocenter Calculator", slug: "orthocenter-calculator" },
      { name: "Pentagon Calculator", slug: "pentagon-calculator" },
      { name: "Perimeter Calculator", slug: "perimeter-calculator" },
      { name: "Quadrilateral Calculator", slug: "quadrilateral-calculator" },
      { name: "Quiz: Area of a Rectangle Calculator", slug: "quiz-area-of-a-rectangle-calculator" },
      { name: "Polygon Calculator", slug: "polygon-calculator" },
      { name: "Segment Addition Postulate Calculator", slug: "segment-addition-postulate-calculator" },
      { name: "Segment Area Calculator", slug: "segment-area-calculator" },
      { name: "Spiral Length Calculator", slug: "spiral-length-calculator" },
      { name: "Square Calc: find A, P, d", slug: "square-calc-find-a-p-d" },
      { name: "Star Shape Calculator", slug: "star-shape-calculator" },
      { name: "Trapezoid Calculator", slug: "trapezoid-calculator" }
    ]
  },
  {
    id: "triangles",
    name: "Triangles",
    calculators: [
      { name: "30 60 90 Triangle Calculator", slug: "30-60-90-triangle-calculator" },
      { name: "45 45 90 Triangle Calculator", slug: "45-45-90-triangle-calculator" },
      { name: "Area of a Right Triangle Calculator", slug: "area-of-a-right-triangle-calculator" },
      { name: "Circumscribed Circle Calculator", slug: "circumscribed-circle-calculator" },
      { name: "Classifying Triangles Calculator", slug: "classifying-triangles-calculator" },
      { name: "Equilateral Triangle Calculator", slug: "equilateral-triangle-calculator" },
      { name: "Heron's Formula Calculator", slug: "heron-s-formula-calculator" },
      { name: "Hypotenuse Calculator", slug: "hypotenuse-calculator" },
      { name: "Isosceles Triangle Calculator", slug: "isosceles-triangle-calculator" },
      { name: "Perimeter of a Triangle Calculator", slug: "perimeter-of-a-triangle-calculator" },
      { name: "Pythagorean Theorem Calculator", slug: "pythagorean-theorem-calculator" },
      { name: "Pythagorean Triples Calculator", slug: "pythagorean-triples-calculator" },
      { name: "Right Triangle Calculator", slug: "right-triangle-calculator" },
      { name: "Right Triangle Side and Angle Calculator", slug: "right-triangle-side-and-angle-calculator" },
      { name: "Similar Triangles Calculator", slug: "similar-triangles-calculator" },
      { name: "Special Right Triangles Calculator", slug: "special-right-triangles-calculator" },
      { name: "Triangle Angle Calculator", slug: "triangle-angle-calculator" },
      { name: "Triangle Area Calculator", slug: "triangle-area-calculator" },
      { name: "Triangle Height Calculator", slug: "triangle-height-calculator" },
      { name: "Triangle Inequality Theorem Calculator", slug: "triangle-inequality-theorem-calculator" }
    ]
  },
  {
    id: "circles",
    name: "Circles",
    calculators: [
      { name: "Arc Length Calculator", slug: "arc-length-calculator" },
      { name: "Area of a Circle Calculator", slug: "area-of-a-circle-calculator" },
      { name: "Circle Calculator", slug: "circle-calculator" },
      { name: "Circle Theorems Calculator", slug: "circle-theorems-calculator" },
      { name: "Circumference Calculator", slug: "circumference-calculator" },
      { name: "Coin Rotation Paradox", slug: "coin-rotation-paradox" },
      { name: "Equation of a Circle Calculator", slug: "equation-of-a-circle-calculator" },
      { name: "Sector Area Calculator", slug: "sector-area-calculator" },
      { name: "Semicircle Area Calculator", slug: "semicircle-area-calculator" },
      { name: "Square in a Circle Calculator", slug: "square-in-a-circle-calculator" },
      { name: "String Girdling Earth Calculator", slug: "string-girdling-earth-calculator" },
      { name: "Tangent of a Circle Calculator", slug: "tangent-of-a-circle-calculator" }
    ]
  },
  {
    id: "angles",
    name: "Angles",
    calculators: [
      { name: "Angle Between Two Vectors Calculator", slug: "angle-between-two-vectors-calculator" },
      { name: "Central Angle Calculator", slug: "central-angle-calculator" },
      { name: "Clock Angle Calculator", slug: "clock-angle-calculator" },
      { name: "Complementary Angles Calculator", slug: "complementary-angles-calculator" },
      { name: "Coterminal Angle Calculator", slug: "coterminal-angle-calculator" },
      { name: "Reference Angle Calculator", slug: "reference-angle-calculator" },
      { name: "Supplementary Angles Calculator", slug: "supplementary-angles-calculator" }
    ]
  },
  {
    id: "3d-geometry",
    name: "3D Geometry",
    calculators: [
      { name: "Surface Area of a Hemisphere Calculator", slug: "surface-area-of-a-hemisphere-calculator" },
      { name: "Cube Calculator", slug: "cube-calculator" },
      { name: "Cube Calc: find V, a, d", slug: "cube-calc-find-v-a-d" },
      { name: "Ellipsoid Volume Calculator", slug: "ellipsoid-volume-calculator" },
      { name: "Great Circle Calculator", slug: "great-circle-calculator" },
      { name: "Lateral Area Trapezoidal Prism Calculator", slug: "lateral-area-trapezoidal-prism-calculator" },
      { name: "Pyramid Angle Calculator", slug: "pyramid-angle-calculator" },
      { name: "Pyramid Volume Calculator", slug: "pyramid-volume-calculator" },
      { name: "Quiz: Cylinder Volume Calculator", slug: "quiz-cylinder-volume-calculator" },
      { name: "Quiz: Cylinder Volume Liters Calculator", slug: "quiz-cylinder-volume-liters-calculator" },
      { name: "Rectangular Prism Calculator", slug: "rectangular-prism-calculator" },
      { name: "Right Circular Cone Calc: find A, V, A_L, A_B.", slug: "right-circular-cone-calc-find-a-v-a-l-a-b" },
      { name: "Right Cylinder Calculator: find A, V, A_l, A_b", slug: "right-cylinder-calculator-find-a-v-a-l-a-b" },
      { name: "Right Rectangular Pyramid Calc: find A, V, A_l, A_b", slug: "right-rectangular-pyramid-calc-find-a-v-a-l-a-b" },
      { name: "Slant Height calculator", slug: "slant-height-calculator" },
      { name: "Sphere Calc: find V, A, d", slug: "sphere-calc-find-v-a-d" },
      { name: "Surface Area Calculator", slug: "surface-area-calculator" },
      { name: "Surface Area of a Triangular Prism Calculator", slug: "surface-area-of-a-triangular-prism-calculator" },
      { name: "Surface Area to Volume Ratio Calculator", slug: "surface-area-to-volume-ratio-calculator" },
      { name: "Tetrahedron Volume Calculator", slug: "tetrahedron-volume-calculator" },
      { name: "Torus Surface Area Calculator", slug: "torus-surface-area-calculator" },
      { name: "Torus Volume Calculator", slug: "torus-volume-calculator" },
      { name: "Triangular Prism Calculator", slug: "triangular-prism-calculator" },
      { name: "Volume Calculator", slug: "volume-calculator" },
      { name: "Volume of a Hemisphere Calculator", slug: "volume-of-a-hemisphere-calculator" },
      { name: "Volume of a Trapezoidal Prism Calculator", slug: "volume-of-a-trapezoidal-prism-calculator" }
    ]
  },
  {
    id: "sequences",
    name: "Sequences",
    calculators: [
      { name: "Arithmetic Sequence Calculator", slug: "arithmetic-sequence-calculator" },
      { name: "Collatz Conjecture Calculator", slug: "collatz-conjecture-calculator" },
      { name: "Convolution Calculator", slug: "convolution-calculator" },
      { name: "Fibonacci Calculator", slug: "fibonacci-calculator" },
      { name: "Geometric Sequence Calculator", slug: "geometric-sequence-calculator" },
      { name: "Harmonic Number Calculator", slug: "harmonic-number-calculator" },
      { name: "Lagrange Error Bound Calculator", slug: "lagrange-error-bound-calculator" },
      { name: "Pascal's Triangle Calculator", slug: "pascals-triangle-calculator" },
      { name: "Sequence Calculator", slug: "sequence-calculator" },
      { name: "Sum of a Linear Number Sequence Calculator", slug: "sum-of-a-linear-number-sequence-calculator" },
      { name: "Sum of Series Calculator", slug: "sum-of-series-calculator" }
    ]
  },
  {
    id: "exponents-logarithms",
    name: "Exponents & Logarithms",
    calculators: [
      { name: "Antilog Calculator – Antilogarithm", slug: "antilog-calculator-antilogarithm" },
      { name: "Change of Base Formula Calculator", slug: "change-of-base-formula-calculator" },
      { name: "Condense Logarithms Calculator", slug: "condense-logarithms-calculator" },
      { name: "Dividing Exponents Calculator", slug: "dividing-exponents-calculator" },
      { name: "Dividing Radicals Calculator", slug: "dividing-radicals-calculator" },
      { name: "e Calculator | eˣ | e Raised to Power of x", slug: "e-calculator-e-raised-to-power-of-x" },
      { name: "Expanding Logarithms Calculator", slug: "expanding-logarithms-calculator" },
      { name: "Exponent Calculator", slug: "exponent-calculator" },
      { name: "Exponential Form Calculator", slug: "exponential-form-calculator" },
      { name: "Exponential Function Calculator", slug: "exponential-function-calculator" },
      { name: "Exponential Growth Calculator", slug: "exponential-growth-calculator" },
      { name: "Log Calculator (Logarithm)", slug: "log-calculator-logarithm" },
      { name: "Log Base 2 Calculator", slug: "log-base-2-calculator" },
      { name: "Multiplying Exponents Calculator", slug: "multiplying-exponents-calculator" },
      { name: "Multiplying Radicals Calculator", slug: "multiplying-radicals-calculator" },
      { name: "Natural Log Calculator", slug: "natural-log-calculator" },
      { name: "Negative Log Calculator", slug: "negative-log-calculator" },
      { name: "Power of a Power Calculator", slug: "power-of-a-power-calculator" }
    ]
  },
  {
    id: "binary",
    name: "Binary & Bitwise",
    calculators: [
      { name: "AND Calculator", slug: "and-calculator" },
      { name: "Binary Addition Calculator", slug: "binary-addition-calculator" },
      { name: "Binary Division Calculator", slug: "binary-division-calculator" },
      { name: "Binary Fraction Converter", slug: "binary-fraction-converter" },
      { name: "Binary Multiplication Calculator", slug: "binary-multiplication-calculator" },
      { name: "Binary Calculator", slug: "binary-calculator" },
      { name: "Binary Subtraction Calculator", slug: "binary-subtraction-calculator" },
      { name: "Bit Shift Calculator", slug: "bit-shift-calculator" },
      { name: "Bitwise Calculator", slug: "bitwise-calculator" },
      { name: "NOR Calculator", slug: "nor-calculator" },
      { name: "One's Complement Calculator", slug: "ones-complement-calculator" },
      { name: "OR Calculator", slug: "or-calculator" },
      { name: "Two's Complement Calculator", slug: "twos-complement-calculator" },
      { name: "XOR Calculator", slug: "xor-calculator" }
    ]
  },
  {
    id: "other-math",
    name: "Other & Paradoxes",
    calculators: [
      { name: "Babylonian Numbers Converter", slug: "babylonian-numbers-converter" },
      { name: "Cyclomatic Complexity Calculator", slug: "cyclomatic-complexity-calculator" },
      { name: "Galileo's Paradox of Infinity Calculator", slug: "galileos-paradox-of-infinity-calculator" },
      { name: "Hilbert's Hotel Paradox Calculator", slug: "hilberts-hotel-paradox-calculator" },
      { name: "Involute Function Calculator", slug: "involute-function-calculator" },
      { name: "LFSR Calculator", slug: "lfsr-calculator" },
      { name: "Luhn Algorithm Calculator", slug: "luhn-algorithm-calculator" },
      { name: "Mayan Numerals Converter", slug: "mayan-numerals-converter" },
      { name: "Miracle Calculator", slug: "miracle-calculator" },
      { name: "Potato Calculator", slug: "potato-calculator" },
      { name: "Prisoner's Dilemma Calculator", slug: "prisoners-dilemma-calculator" },
      { name: "Queueing Theory Calculator", slug: "queueing-theory-calculator" },
      { name: "RSA Calculator", slug: "rsa-calculator" },
      { name: "Ugly Duckling Theorem Calculator", slug: "ugly-duckling-theorem-calculator" }
    ]
  }
];
