import { GraduationCap, Camera, Music, Monitor, Wifi, Gamepad2, Truck, Calendar, Earth, Package } from 'lucide-react';

export const OTHER_DATA = [
  {
    id: "education",
    title: "Education calculators 🎓",
    icon: GraduationCap,
    calculators: [
      { name: "ACT Score Calculator", slug: "act-score-calculator" },
      { name: "Classroom Spacing Calculator - Coronavirus", slug: "classroom-spacing-calculator" },
      { name: "College GPA Calculator", slug: "college-gpa-calculator" },
      { name: "Final Grade Calculator", slug: "final-grade-calculator" },
      { name: "GPA Calculator", slug: "gpa-calculator" },
      { name: "GPA Calculator Pakistan", slug: "gpa-calculator-pakistan" },
      { name: "Grade Calculator", slug: "grade-calculator" },
      { name: "Grade Curve Calculator", slug: "grade-curve-calculator" },
      { name: "Graduation Year Calculator", slug: "graduation-year-calculator" },
      { name: "GWA Calculator – General Weighted Average", slug: "gwa-calculator" },
      { name: "High School GPA Calculator", slug: "high-school-gpa-calculator" },
      { name: "IELTS Score Calculator", slug: "ielts-score-calculator" },
      { name: "Impact Factor Calculator", slug: "impact-factor-calculator" },
      { name: "PTE Score Calculator", slug: "pte-score-calculator" },
      { name: "Semester Grade Calculator", slug: "semester-grade-calculator" },
      { name: "Test Grade Calculator", slug: "test-grade-calculator" }
    ]
  },
  {
    id: "photo-video",
    title: "Photo and video calculators 📷",
    icon: Camera,
    calculators: [
      { name: "3D Render Calculator", slug: "3d-render-calculator" },
      { name: "Aspect Ratio Calculator", slug: "aspect-ratio-calculator" },
      { name: "Blink-free Photo Calculator", slug: "blink-free-photo-calculator" },
      { name: "Camera Field of View Calculator", slug: "camera-field-of-view" },
      { name: "Contrast Ratio Calculator", slug: "contrast-ratio-calculator" },
      { name: "Crop Factor Calculator", slug: "crop-factor-calculator" },
      { name: "Depth of Field Calculator", slug: "depth-of-field-calculator" },
      { name: "Exposure Calculator", slug: "exposure-calculator" },
      { name: "Film Calculator", slug: "film-calculator" },
      { name: "Focal Length Calculator", slug: "focal-length-calculator" },
      { name: "Frames to Timecode Calculator", slug: "frames-to-timecode" },
      { name: "Hyperfocal Distance Calculator", slug: "hyperfocal-distance-calculator" },
      { name: "Image File Size Calculator", slug: "image-file-size-calculator" },
      { name: "Image Ratio Calculator", slug: "image-ratio-calculator" },
      { name: "Magnification of a Lens Calculator", slug: "magnification-lens-calculator" },
      { name: "Pixels to Print Size Calculator", slug: "pixels-to-print-size" },
      { name: "PPI Calculator (Pixels Per Inch)", slug: "ppi-calculator" },
      { name: "Projector Calculator", slug: "projector-calculator" },
      { name: "Resolution Scale Calculator", slug: "resolution-scale-calculator" },
      { name: "Screen Size Calculator", slug: "screen-size-calculator" },
      { name: "Shutter Speed Calculator", slug: "shutter-speed-calculator" },
      { name: "Timecode to Frames Calculator", slug: "timecode-to-frames" },
      { name: "Time Lapse Calculator", slug: "time-lapse-calculator" },
      { name: "TV Mounting Height Calculator", slug: "tv-mounting-height-calculator" },
      { name: "TV Size Calculator", slug: "tv-size-calculator" },
      { name: "Vertical Exaggeration Calculator", slug: "vertical-exaggeration-calculator" },
      { name: "Video File Size Calculator (by format)", slug: "video-file-size-calculator" },
      { name: "Video Frame Size Calculator", slug: "video-frame-size-calculator" }
    ]
  },
  {
    id: "music",
    title: "Music calculators 🎵",
    icon: Music,
    calculators: [
      { name: "Audio File Size Calculator", slug: "audio-file-size-calculator" },
      { name: "BPM Calculator", slug: "bpm-calculator" },
      { name: "Chord Calculator", slug: "chord-calculator" },
      { name: "Chord Finder", slug: "chord-finder" },
      { name: "Chord Inversion Calculator", slug: "chord-inversion-calculator" },
      { name: "Chord Progression Generator", slug: "chord-progression-generator" },
      { name: "Chord Transposer", slug: "chord-transposer" },
      { name: "Delay and Reverb Calculator", slug: "delay-and-reverb-calculator" },
      { name: "Fret Calculator", slug: "fret-calculator" },
      { name: "Guitar String Tension Calculator", slug: "guitar-string-tension-calculator" },
      { name: "Harmonic Series Calculator", slug: "harmonic-series-calculator" },
      { name: "Key Signature Calculator", slug: "key-signature-calculator" },
      { name: "Music Duration Calculator", slug: "music-duration-calculator" },
      { name: "Music Interval Calculator", slug: "music-interval-calculator" },
      { name: "Music Scale Calculator", slug: "music-scale-calculator" },
      { name: "Music Transposition Calculator", slug: "music-transposition-calculator" },
      { name: "Note Frequency Calculator", slug: "note-frequency-calculator" },
      { name: "Port Length Calculator", slug: "port-length-calculator" },
      { name: "Quiz: Port Length Calculator", slug: "quiz-port-length-calculator" },
      { name: "Semitone Calculator", slug: "semitone-calculator" },
      { name: "Speaker Box Calculator", slug: "speaker-box-calculator" },
      { name: "Vocal Range Calculator", slug: "vocal-range-calculator" }
    ]
  },
  {
    id: "tech-electronics",
    title: "Tech and electronics calculators 💻",
    icon: Monitor,
    calculators: [
      { name: "3D Printing Cost Calculator", slug: "3d-printing-cost-calculator" },
      { name: "Amdahl's Law Calculator", slug: "amdahls-law-calculator" },
      { name: "ASCII Converter", slug: "ascii-converter" },
      { name: "Battery Capacity Calculator", slug: "battery-capacity-calculator" },
      { name: "Battery Life Calculator", slug: "battery-life-calculator" },
      { name: "Battery Size Calculator", slug: "battery-size-calculator" },
      { name: "Binary to Text Converter", slug: "binary-to-text-converter" },
      { name: "Cable Impedance Calculator", slug: "cable-impedance-calculator" },
      { name: "Capital Case Converter", slug: "capital-case-converter" },
      { name: "Chmod Calculator", slug: "chmod-calculator" },
      { name: "CIDR Calculator", slug: "cidr-calculator" },
      { name: "Crosstalk Calculator", slug: "crosstalk-calculator" },
      { name: "Drone Flight Time Calculator", slug: "drone-flight-time-calculator" },
      { name: "Drone Motor Calculator", slug: "drone-motor-calculator" },
      { name: "Duty Cycle Calculator", slug: "duty-cycle-calculator" },
      { name: "eDPI Calculator", slug: "edpi-calculator" },
      { name: "Floating-Point Calculator", slug: "floating-point-calculator" },
      { name: "Gothic Font Generator", slug: "gothic-font-generator" },
      { name: "GSD Calculator – Ground Sample Distance", slug: "gsd-calculator" },
      { name: "Hamming Code Calculator", slug: "hamming-code-calculator" },
      { name: "Hamming Distance Calculator", slug: "hamming-distance-calculator" },
      { name: "Hash Identifier", slug: "hash-identifier" },
      { name: "Hex-to-Text Converter", slug: "hex-to-text-converter" },
      { name: "Impedance Matching Calculator", slug: "impedance-matching-calculator" },
      { name: "Letters to Numbers Converter", slug: "letters-to-numbers-converter" },
      { name: "LM317 Calculator", slug: "lm317-calculator" },
      { name: "Logic Gate Calculator", slug: "logic-gate-calculator" },
      { name: "Mirror Text Generator", slug: "mirror-text-generator" },
      { name: "Morse Code Translator", slug: "morse-code-translator" },
      { name: "Numbers to Letters Converter", slug: "numbers-to-letters-converter" },
      { name: "Op-Amp Gain Calculator", slug: "op-amp-gain-calculator" },
      { name: "Parity Bit Calculator", slug: "parity-bit-calculator" },
      { name: "Password Entropy Calculator", slug: "password-entropy-calculator" },
      { name: "PCB Impedance Calculator", slug: "pcb-impedance-calculator" },
      { name: "PCB Trace Current Calculator", slug: "pcb-trace-current-calculator" },
      { name: "PCB Trace Resistance Calculator", slug: "pcb-trace-resistance-calculator" },
      { name: "PCB Trace Width Calculator", slug: "pcb-trace-width-calculator" },
      { name: "Pi Attenuator Calculator", slug: "pi-attenuator-calculator" },
      { name: "Propagation Delay Calculator", slug: "propagation-delay-calculator" },
      { name: "RAID Calculator", slug: "raid-calculator" },
      { name: "RAM Latency Calculator", slug: "ram-latency-calculator" },
      { name: "RF Unit Converter", slug: "rf-unit-converter" },
      { name: "Sentence Case Converter", slug: "sentence-case-converter" },
      { name: "Small Caps Generator", slug: "small-caps-generator" },
      { name: "Small Text Generator", slug: "small-text-generator" },
      { name: "Strikethrough Text Generator", slug: "strikethrough-text-generator" },
      { name: "Subscript Generator", slug: "subscript-generator" },
      { name: "Superscript Generator", slug: "superscript-generator" },
      { name: "T9 to Text Converter", slug: "t9-to-text-converter" },
      { name: "Text to Binary Converter", slug: "text-to-binary-converter" },
      { name: "Text-to-Hexadecimal Converter", slug: "text-to-hexadecimal-converter" },
      { name: "Title Case Converter", slug: "title-case-converter" },
      { name: "Total Harmonic Distortion Calculator", slug: "total-harmonic-distortion-calculator" },
      { name: "Vigenère Cipher Calculator", slug: "vigenere-cipher-calculator" },
      { name: "Wingdings Translator", slug: "wingdings-translator" }
    ]
  },
  {
    id: "internet-network",
    title: "Internet and network calculators 📡",
    icon: Wifi,
    calculators: [
      { name: "Bandwidth Calculator", slug: "bandwidth-calculator" },
      { name: "Bandwidth Delay Product Calculator", slug: "bandwidth-delay-product-calculator" },
      { name: "Base64 Encoder & Decoder", slug: "base64-encoder-decoder" },
      { name: "Baud Rate Calculator", slug: "baud-rate-calculator" },
      { name: "Data Transfer Calculator", slug: "data-transfer-calculator" },
      { name: "Download Time Calculator", slug: "download-time-calculator" },
      { name: "IP Address Converter", slug: "ip-address-converter" },
      { name: "IP Subnet Calculator", slug: "ip-subnet-calculator" },
      { name: "Streaming Bitrate Calculator", slug: "streaming-bitrate-calculator" },
      { name: "Upload Time Calculator", slug: "upload-time-calculator" },
      { name: "Uptime Calculator", slug: "uptime-calculator" }
    ]
  },
  {
    id: "video-games",
    title: "Video games calculators 🎮",
    icon: Gamepad2,
    calculators: [
      { name: "Impostor Odds Calculator – Among Us", slug: "impostor-odds-among-us" },
      { name: "KD Calculator (Kill/Death Ratio)", slug: "kd-calculator" },
      { name: "Minecraft Circle Generator", slug: "minecraft-circle-generator" },
      { name: "Minecraft End Portal Finder", slug: "minecraft-end-portal-finder" },
      { name: "Minecraft Stack Calculator", slug: "minecraft-stack-calculator" },
      { name: "Nether Portal Calculator", slug: "nether-portal-calculator" },
      { name: "Pokémon Go Candy Calculator", slug: "pokemon-go-candy-calculator" },
      { name: "Pyramid Block Calculator", slug: "pyramid-block-calculator" },
      { name: "Rust Decay Calculator", slug: "rust-decay-calculator" },
      { name: "The Witcher: Monster Slayer Calculator", slug: "witcher-monster-slayer-calculator" }
    ]
  },
  {
    id: "logistics",
    title: "Logistics calculators 🚚",
    icon: Truck,
    calculators: [
      { name: "CBM Calculator for Shipping", slug: "cbm-calculator-shipping" },
      { name: "Container Loading Calculator", slug: "container-loading-calculator" },
      { name: "Dimensional Weight Calculator", slug: "dimensional-weight-calculator" },
      { name: "DPMO Calculator", slug: "dpmo-calculator" },
      { name: "Freight Class Calculator", slug: "freight-class-calculator" },
      { name: "Pallet Calculator", slug: "pallet-calculator" },
      { name: "Reorder Point Calculator", slug: "reorder-point-calculator" },
      { name: "Takt Time Calculator", slug: "takt-time-calculator" }
    ]
  },
  {
    id: "seasons-holidays",
    title: "Seasons and holidays calculators 🎃",
    icon: Calendar,
    calculators: [
      { name: "Christmas Tree Calculator", slug: "christmas-tree-calculator" },
      { name: "Christmas Countdown Calculator", slug: "christmas-countdown-calculator" },
      { name: "Easter Calculator", slug: "easter-calculator" },
      { name: "Vampire Apocalypse Calculator", slug: "vampire-apocalypse-calculator" },
      { name: "Mayan Calendar Converter", slug: "mayan-calendar-converter" },
      { name: "New Year's Resolutions Calculator", slug: "new-years-resolutions-calculator" },
      { name: "Snowman Calculator", slug: "snowman-calculator" },
      { name: "Trick-or-Treat Calculator", slug: "trick-or-treat-calculator" },
      { name: "White Christmas Calculator", slug: "white-christmas-calculator" },
      { name: "Zombie Invasion Calculator", slug: "zombie-invasion-calculator" }
    ]
  },
  {
    id: "earth-weather",
    title: "Earth and weather calculators 🌎",
    icon: Earth,
    calculators: [
      { name: "Antipode Calculator", slug: "antipode-calculator" },
      { name: "Azimuth Calculator", slug: "azimuth-calculator" },
      { name: "Earthquake Calculator", slug: "earthquake-calculator" },
      { name: "Latitude Longitude Distance Calculator", slug: "latitude-longitude-distance-calculator" },
      { name: "Rainfall Calculator", slug: "rainfall-calculator" },
      { name: "Rain to Snow Calculator", slug: "rain-to-snow-calculator" },
      { name: "Sunbathing Calculator", slug: "sunbathing-calculator" },
      { name: "Wind Chill Calculator", slug: "wind-chill-calculator" }
    ]
  },
  {
    id: "miscellaneous-other",
    title: "Other calculators",
    icon: Package,
    calculators: [
      { name: "Age on Other Planets Calculator", slug: "age-on-other-planets-calculator" },
      { name: "Angle of Impact Calculator", slug: "angle-of-impact-calculator" },
      { name: "Aquarium Calculator", slug: "aquarium-calculator" },
      { name: "Aquarium Glass Thickness Calculator", slug: "aquarium-glass-thickness-calculator" },
      { name: "Caesar Cipher Shifter", slug: "caesar-cipher-shifter" },
      { name: "Recruitment Process Duration Calculator", slug: "recruitment-process-duration-calculator" },
      { name: "Day of the Week Calculator", slug: "day-of-the-week-calculator" },
      { name: "Diamond Weight Calculator", slug: "diamond-weight-calculator" },
      { name: "Encounter Calculator 5e", slug: "encounter-calculator-5e" },
      { name: "Engagement Rate Calculator", slug: "engagement-rate-calculator" },
      { name: "Flag Calculator | USA", slug: "flag-calculator-usa" },
      { name: "Gender Pay Gap Calculator", slug: "gender-pay-gap-calculator" },
      { name: "Cost of Hiring an Expert vs. Hiring a Fresher Calculator", slug: "cost-hiring-expert-vs-fresher" },
      { name: "HP Calculator 5e – Dungeons & Dragons", slug: "hp-calculator-5e" },
      { name: "Matched Betting Calculator", slug: "matched-betting-calculator" },
      { name: "NaNoWriMo Calculator", slug: "nanowrimo-calculator" },
      { name: "Oxygen Tank Duration Calculator", slug: "oxygen-tank-duration-calculator" },
      { name: "Pay Gap Calculator", slug: "pay-gap-calculator" },
      { name: "PERT Calculator", slug: "pert-calculator" },
      { name: "Pizza Tip Calculator", slug: "pizza-tip-calculator" },
      { name: "Point Buy Calculator 5e", slug: "point-buy-calculator-5e" },
      { name: "Poker EV Calculator", slug: "poker-ev-calculator" },
      { name: "Poker Odds Calculator", slug: "poker-odds-calculator" },
      { name: "Rounds per Minute Calculator", slug: "rounds-per-minute-calculator" },
      { name: "Salt Dough Calculator", slug: "salt-dough-calculator" },
      { name: "Sandbox Calculator", slug: "sandbox-calculator" },
      { name: "Dating Theory Calculator", slug: "dating-theory-calculator" },
      { name: "Streaming Services' Royalties Calculator", slug: "streaming-services-royalties-calculator" },
      { name: "TIP CALCULATOR", slug: "tip-calculator" },
      { name: "Tip from Net Price Calculator", slug: "tip-from-net-price-calculator" },
      { name: "Travel Expenses", slug: "travel-expenses" }
    ]
  }
];
