import { Timer, ArrowRight, Scale, Zap, Wrench, Telescope, Atom, Cpu, Droplets, Cloud, Thermometer, FlaskConical, Beaker } from 'lucide-react';

export const PHYSICS_DATA = [
  {
    id: "kinematics",
    title: "Kinematics calculators — How things move ⏱️",
    icon: Timer,
    calculators: [
      { name: "Arrow Speed Calculator", slug: "arrow-speed-calculator" },
      { name: "Ballistic Coefficient Calculator", slug: "ballistic-coefficient-calculator" },
      { name: "Car Jump Distance Calculator", slug: "car-jump-distance-calculator" },
      { name: "Conservation of Momentum Calculator", slug: "conservation-of-momentum-calculator" },
      { name: "Displacement Calculator", slug: "displacement-calculator" },
      { name: "Free Fall Calculator", slug: "free-fall-calculator" },
      { name: "Free Fall with Air Resistance Calculator", slug: "free-fall-with-air-resistance-calculator" },
      { name: "Friction Calculator", slug: "friction-calculator" },
      { name: "Ground Speed Calculator", slug: "ground-speed-calculator" },
      { name: "Horizontal Projectile Motion Calculator", slug: "horizontal-projectile-motion-calculator" },
      { name: "Impulse and Momentum Calculator", slug: "impulse-and-momentum-calculator" },
      { name: "Inclined Plane Calculator", slug: "inclined-plane-calculator" },
      { name: "Magnitude of Acceleration Calculator", slug: "magnitude-of-acceleration-calculator" },
      { name: "Maximum Height Calculator – Projectile Motion", slug: "maximum-height-calculator-projectile-motion" },
      { name: "MOA Calculator — Minute of Angle", slug: "moa-calculator-minute-of-angle" },
      { name: "Momentum Calculator", slug: "momentum-calculator" },
      { name: "Muzzle Velocity Calculator", slug: "muzzle-velocity-calculator" },
      { name: "Polar Moment of Inertia Calculator", slug: "polar-moment-of-inertia-calculator" },
      { name: "Projectile Motion Calculator", slug: "projectile-motion-calculator" },
      { name: "Projectile Range Calculator", slug: "projectile-range-calculator" },
      { name: "Quarter Mile Calculator", slug: "quarter-mile-calculator" },
      { name: "Resultant Velocity Calculator", slug: "resultant-velocity-calculator" },
      { name: "Rolling Resistance Calculator", slug: "rolling-resistance-calculator" },
      { name: "Sled Ride Calculator", slug: "sled-ride-calculator" },
      { name: "SUVAT Calculator", slug: "suvat-calculator" },
      { name: "Terminal Velocity Calculator", slug: "terminal-velocity-calculator" },
      { name: "Time of Flight Calculator – Projectile Motion", slug: "time-of-flight-calculator-projectile-motion" },
      { name: "Trajectory Calculator", slug: "trajectory-calculator" },
      { name: "Velocity Calculator", slug: "velocity-calculator" }
    ]
  },
  {
    id: "dynamics",
    title: "Dynamics calculators — Why things move ➡️",
    icon: ArrowRight,
    calculators: [
      { name: "Acceleration Calculator", slug: "acceleration-calculator" },
      { name: "Angle of Banking Calculator", slug: "angle-of-banking-calculator" },
      { name: "Car Crash Calculator", slug: "car-crash-calculator" },
      { name: "Force Calculator", slug: "force-calculator" },
      { name: "Gravitational Force Calculator", slug: "gravitational-force-calculator" },
      { name: "Hooke's Law Calculator", slug: "hookes-law-calculator" },
      { name: "kg to Newtons Calculator", slug: "kg-to-newtons-calculator" },
      { name: "Newton's Second Law Calculator", slug: "newtons-second-law-calculator" },
      { name: "Newton's Third Law Calculator", slug: "newtons-third-law-calculator" },
      { name: "Normal Force Calculator", slug: "normal-force-calculator" },
      { name: "Net Force Calculator", slug: "net-force-calculator" },
      { name: "Stopping Distance Calculator", slug: "stopping-distance-calculator" },
      { name: "Tension Calculator", slug: "tension-calculator" }
    ]
  },
  {
    id: "statics",
    title: "Statics calculators — When things don't move ⚖️",
    icon: Scale,
    calculators: [
      { name: "Car Center of Mass Calculator", slug: "car-center-of-mass-calculator" },
      { name: "Pounds per Square Inch Calculator", slug: "pounds-per-square-inch-calculator" },
      { name: "Pressure Calculator", slug: "pressure-calculator" },
      { name: "Reduced Mass Calculator", slug: "reduced-mass-calculator" },
      { name: "Weight on Other Planets Calculator", slug: "weight-on-other-planets-calculator" }
    ]
  },
  {
    id: "energy-work-power",
    title: "Energy, work, and power calculators ⚡",
    icon: Zap,
    calculators: [
      { name: "Bullet Energy Calculator", slug: "bullet-energy-calculator" },
      { name: "EIRP Calculator — Effective Isotropic Radiated Power", slug: "eirp-calculator" },
      { name: "Elastic Potential Energy Calculator", slug: "elastic-potential-energy-calculator" },
      { name: "FPE Calculator — Foot-pounds of Energy", slug: "fpe-calculator" },
      { name: "Impact Energy Calculator", slug: "impact-energy-calculator" },
      { name: "Kinetic Energy Calculator", slug: "kinetic-energy-calculator" },
      { name: "Potential Energy Calculator", slug: "potential-energy-calculator" },
      { name: "Power-to-Weight Ratio Calculator", slug: "power-to-weight-ratio-calculator" },
      { name: "Recoil Energy Calculator", slug: "recoil-energy-calculator" },
      { name: "Signal-to-Noise Ratio Calculator", slug: "signal-to-noise-ratio-calculator" },
      { name: "TNT Equivalent Calculator", slug: "tnt-equivalent-calculator" },
      { name: "Watt Converter", slug: "watt-converter" },
      { name: "Work Calculator", slug: "work-calculator" },
      { name: "Work and Power Calculator", slug: "work-and-power-calculator" }
    ]
  },
  {
    id: "rotational-periodic",
    title: "Rotational and periodic motion calculators 🌎",
    icon: Zap,
    calculators: [
      { name: "Angular Acceleration Calculator", slug: "angular-acceleration-calculator" },
      { name: "Angular Displacement Calculator", slug: "angular-displacement-calculator" },
      { name: "Angular Frequency Calculator", slug: "angular-frequency-calculator" },
      { name: "Angular Momentum Calculator", slug: "angular-momentum-calculator" },
      { name: "Angular Velocity Calculator", slug: "angular-velocity-calculator" },
      { name: "Centrifugal Force Calculator", slug: "centrifugal-force-calculator" },
      { name: "Centrifuge Calculator", slug: "centrifuge-calculator" },
      { name: "Centripetal Force Calculator", slug: "centripetal-force-calculator" },
      { name: "Circular Motion Calculator", slug: "circular-motion-calculator" },
      { name: "Coriolis Effect Calculator", slug: "coriolis-effect-calculator" },
      { name: "Damping Ratio Calculator", slug: "damping-ratio-calculator" },
      { name: "Flywheel Energy Storage Calculator", slug: "flywheel-energy-storage-calculator" },
      { name: "Frequency Calculator", slug: "frequency-calculator" },
      { name: "Harmonic Wave Equation Calculator", slug: "harmonic-wave-equation-calculator" },
      { name: "Kinetic Energy of a Pendulum Calculator", slug: "kinetic-energy-of-a-pendulum-calculator" },
      { name: "Mass Moment of Inertia Calculator", slug: "mass-moment-of-inertia-calculator" },
      { name: "Physical Pendulum Calculator", slug: "physical-pendulum-calculator" },
      { name: "Rotational Kinetic Energy Calculator", slug: "rotational-kinetic-energy-calculator" },
      { name: "Rotational Stiffness Calculator", slug: "rotational-stiffness-calculator" },
      { name: "Simple Harmonic Motion Calculator", slug: "simple-harmonic-motion-calculator" },
      { name: "Simple Pendulum Calculator", slug: "simple-pendulum-calculator" },
      { name: "Torque Calculator", slug: "torque-calculator" },
      { name: "Wavelength Calculator", slug: "wavelength-calculator" }
    ]
  },
  {
    id: "optics-light",
    title: "Optics and light calculators 🔍",
    icon: Zap,
    calculators: [
      { name: "Angular Resolution Calculator", slug: "angular-resolution-calculator" },
      { name: "Aperture Area Calculator", slug: "aperture-area-calculator" },
      { name: "Binoculars Range Calculator", slug: "binoculars-range-calculator" },
      { name: "Blackbody Radiation Calculator", slug: "blackbody-radiation-calculator" },
      { name: "Bragg's Law Calculator", slug: "braggs-law-calculator" },
      { name: "Brewster's Angle Calculator", slug: "brewsters-angle-calculator" },
      { name: "Contact Lens Vertex Calculator", slug: "contact-lens-vertex-calculator" },
      { name: "Diffraction Grating Calculator", slug: "diffraction-grating-calculator" },
      { name: "Diopter Calculator", slug: "diopter-calculator" },
      { name: "Distance to Horizon Calculator", slug: "distance-to-horizon-calculator" },
      { name: "Earth Curvature Calculator", slug: "earth-curvature-calculator" },
      { name: "Index of Refraction Calculator", slug: "index-of-refraction-calculator" },
      { name: "Laser Beam Divergence Calculator", slug: "laser-beam-divergence-calculator" },
      { name: "Laser Beam Expander Calculator", slug: "laser-beam-expander-calculator" },
      { name: "Laser Brightness Calculator", slug: "laser-brightness-calculator" },
      { name: "Laser Linewidth and Bandwidth Calculator", slug: "laser-linewidth-and-bandwidth-calculator" },
      { name: "Laser Beam Spot Size Calculator", slug: "laser-beam-spot-size-calculator" },
      { name: "Lens Maker Equation Calculator", slug: "lens-maker-equation-calculator" },
      { name: "Lumen Calculator", slug: "lumen-calculator" },
      { name: "Lux to Foot Candles Converter", slug: "lux-to-foot-candles-converter" },
      { name: "Malus Law Calculator", slug: "malus-law-calculator" },
      { name: "Mirror Equation Calculator", slug: "mirror-equation-calculator" },
      { name: "Optical Density Calculator", slug: "optical-density-calculator" },
      { name: "Radar Horizon Calculator", slug: "radar-horizon-calculator" },
      { name: "Snell's Law Calculator", slug: "snells-law-calculator" },
      { name: "Speed of Light Calculator", slug: "speed-of-light-calculator" },
      { name: "Telescope Field of View Calculator", slug: "telescope-field-of-view-calculator" },
      { name: "Telescope Magnification Calculator", slug: "telescope-magnification-calculator" },
      { name: "Thin-Film Optical Coating Calculator", slug: "thin-film-optical-coating-calculator" },
      { name: "Thin Lens Equation Calculator", slug: "thin-lens-equation-calculator" }
    ]
  },
  {
    id: "materials-continuum",
    title: "Materials and continuum mechanics calculators 🧱",
    icon: Wrench,
    calculators: [
      { name: "Angle of Repose Calculator", slug: "angle-of-repose-calculator" },
      { name: "Angle of Twist Calculator", slug: "angle-of-twist-calculator" },
      { name: "Bend Allowance Calculator", slug: "bend-allowance-calculator" },
      { name: "Brinell Hardness Number Calculator", slug: "brinell-hardness-number-calculator" },
      { name: "Buckling Calculator", slug: "buckling-calculator" },
      { name: "Bulk Modulus Calculator", slug: "bulk-modulus-calculator" },
      { name: "Copper Wire Weight Calculator", slug: "copper-wire-weight-calculator" },
      { name: "Density Calculator", slug: "density-calculator" },
      { name: "Elastic Constants Calculator", slug: "elastic-constants-calculator" },
      { name: "Elongation Calculator", slug: "elongation-calculator" },
      { name: "Factor of Safety Calculator", slug: "factor-of-safety-calculator" },
      { name: "Gold Weight Calculator", slug: "gold-weight-calculator" },
      { name: "Hoop Stress Calculator", slug: "hoop-stress-calculator" },
      { name: "Impact Test Calculator", slug: "impact-test-calculator" },
      { name: "Intrinsic Carrier Concentration Calculator", slug: "intrinsic-carrier-concentration-calculator" },
      { name: "Mohr's Circle Calculator", slug: "mohrs-circle-calculator" },
      { name: "Natural Frequency Calculator", slug: "natural-frequency-calculator" },
      { name: "Number Density Calculator", slug: "number-density-calculator" },
      { name: "Poisson's Ratio Calculator", slug: "poissons-ratio-calculator" },
      { name: "Principal Stress Calculator", slug: "principal-stress-calculator" },
      { name: "Rockwell Hardness Conversion Calculator", slug: "rockwell-hardness-conversion-calculator" },
      { name: "Section Modulus Calculator", slug: "section-modulus-calculator" },
      { name: "Shear Modulus Calculator", slug: "shear-modulus-calculator" },
      { name: "Shear Strain Calculator", slug: "shear-strain-calculator" },
      { name: "Shear Stress Calculator", slug: "shear-stress-calculator" },
      { name: "Shear Wave Velocity Calculator", slug: "shear-wave-velocity-calculator" },
      { name: "Slenderness Ratio Calculator", slug: "slenderness-ratio-calculator" },
      { name: "Specific Gravity Calculator", slug: "specific-gravity-calculator" },
      { name: "Stiffness Matrix Calculator", slug: "stiffness-matrix-calculator" },
      { name: "Stress Calculator", slug: "stress-calculator" },
      { name: "Stress Concentration Factor Calculator", slug: "stress-concentration-factor-calculator" },
      { name: "Thermal Stress Calculator", slug: "thermal-stress-calculator" },
      { name: "Torsional Constant Calculator", slug: "torsional-constant-calculator" },
      { name: "Torsional Stiffness Calculator", slug: "torsional-stiffness-calculator" },
      { name: "True Strain Calculator", slug: "true-strain-calculator" },
      { name: "Vickers Hardness Number Calculator", slug: "vickers-hardness-number-calculator" },
      { name: "Volume to Mass Calculator", slug: "volume-to-mass-calculator" },
      { name: "Von Mises Stress Calculator", slug: "von-mises-stress-calculator" },
      { name: "Young's Modulus Calculator", slug: "youngs-modulus-calculator" }
    ]
  },
  {
    id: "machines-mechanisms",
    title: "Machines and mechanisms calculators 🔩",
    icon: Wrench,
    calculators: [
      { name: "Belt Length Calculator", slug: "belt-length-calculator" },
      { name: "BMEP Calculator", slug: "bmep-calculator" },
      { name: "Carburetor CFM Calculator", slug: "carburetor-cfm-calculator" },
      { name: "Crawl Ratio Calculator", slug: "crawl-ratio-calculator" },
      { name: "Engine Displacement Calculator", slug: "engine-displacement-calculator" },
      { name: "Exhaust Diameter Calculator", slug: "exhaust-diameter-calculator" },
      { name: "Fulcrum Calculator", slug: "fulcrum-calculator" },
      { name: "Gear Ratio Calculator", slug: "gear-ratio-calculator" },
      { name: "Lever Calculator", slug: "lever-calculator" },
      { name: "Linear Actuator Force Calculator", slug: "linear-actuator-force-calculator" },
      { name: "Mechanical Advantage Calculator", slug: "mechanical-advantage-calculator" },
      { name: "NPSH Calculator", slug: "npsh-calculator" },
      { name: "Piston Force Calculator", slug: "piston-force-calculator" },
      { name: "Piston Speed Calculator", slug: "piston-speed-calculator" },
      { name: "Prop Pitch Calculator", slug: "prop-pitch-calculator" },
      { name: "Prop Slip Calculator", slug: "prop-slip-calculator" },
      { name: "Pulley Calculator", slug: "pulley-calculator" },
      { name: "Pump Horsepower Calculator", slug: "pump-horsepower-calculator" },
      { name: "Shaft Size Calculator", slug: "shaft-size-calculator" },
      { name: "Speeds and Feeds Calculator", slug: "speeds-and-feeds-calculator" },
      { name: "Spring Calculator", slug: "spring-calculator" },
      { name: "Spring Rate Calculator", slug: "spring-rate-calculator" },
      { name: "Spring Rate Converter", slug: "spring-rate-converter" },
      { name: "Torsion Spring Calculator", slug: "torsion-spring-calculator" },
      { name: "Transmission Calculator", slug: "transmission-calculator" },
      { name: "Twist Rate Calculator", slug: "twist-rate-calculator" },
      { name: "Wing Loading Calculator", slug: "wing-loading-calculator" }
    ]
  },
  {
    id: "astronomy",
    title: "Astronomy calculators 🪐",
    icon: Telescope,
    calculators: [
      { name: "Alien Civilization Calculator", slug: "alien-civilization-calculator" },
      { name: "Delta V Calculator", slug: "delta-v-calculator" },
      { name: "Earth Orbit Calculator", slug: "earth-orbit-calculator" },
      { name: "Escape Velocity Calculator", slug: "escape-velocity-calculator" },
      { name: "Exoplanet Discovery Calculator", slug: "exoplanet-discovery-calculator" },
      { name: "Hohmann Transfer Calculator", slug: "hohmann-transfer-calculator" },
      { name: "Rocket Equation Calculator", slug: "rocket-equation-calculator" },
      { name: "Kepler's Third Law Calculator", slug: "keplers-third-law-calculator" },
      { name: "Orbital Period Calculator", slug: "orbital-period-calculator" },
      { name: "Orbital Velocity Calculator", slug: "orbital-velocity-calculator" },
      { name: "Rocket Thrust Calculator", slug: "rocket-thrust-calculator" },
      { name: "Specific Impulse Calculator", slug: "specific-impulse-calculator" },
      { name: "Synodic Period Calculator", slug: "synodic-period-calculator" },
      { name: "Thrust to Weight Ratio Calculator", slug: "thrust-to-weight-ratio-calculator" },
      { name: "UFO Travel Calculator", slug: "ufo-travel-calculator" }
    ]
  },
  {
    id: "astrophysics",
    title: "Astrophysics calculators 🌌",
    icon: Telescope,
    calculators: [
      { name: "Black Hole Collision Calculator", slug: "black-hole-collision-calculator" },
      { name: "Black Hole Temperature Calculator", slug: "black-hole-temperature-calculator" },
      { name: "Drake Equation Calculator", slug: "drake-equation-calculator" },
      { name: "Hubble Law Distance Calculator", slug: "hubble-law-distance-calculator" },
      { name: "Light Year Calculator", slug: "light-year-calculator" },
      { name: "Luminosity Calculator", slug: "luminosity-calculator" },
      { name: "Olber's Paradox Calculator", slug: "olbers-paradox-calculator" },
      { name: "Parallax Calculator", slug: "parallax-calculator" },
      { name: "Radiation Pressure Calculator", slug: "radiation-pressure-calculator" },
      { name: "Redshift Calculator", slug: "redshift-calculator" },
      { name: "Schwarzschild Radius Calculator", slug: "schwarzschild-radius-calculator" },
      { name: "Universe Expansion Calculator", slug: "universe-expansion-calculator" }
    ]
  },
  {
    id: "relativity",
    title: "Relativity calculators 🚀",
    icon: Zap,
    calculators: [
      { name: "Barn-Pole Paradox Calculator", slug: "barn-pole-paradox-calculator" },
      { name: "Bug-Rivet Paradox Calculator", slug: "bug-rivet-paradox-calculator" },
      { name: "Electron Speed Calculator", slug: "electron-speed-calculator" },
      { name: "E = mc² Calculator", slug: "e-mc2-calculator" },
      { name: "Gravitational Time Dilation Calculator", slug: "gravitational-time-dilation-calculator" },
      { name: "Length Contraction Calculator", slug: "length-contraction-calculator" },
      { name: "Relativistic Kinetic Energy Calculator", slug: "relativistic-kinetic-energy-calculator" },
      { name: "Space Travel Calculator", slug: "space-travel-calculator" },
      { name: "Time Dilation Calculator", slug: "time-dilation-calculator" },
      { name: "Velocity Addition Calculator", slug: "velocity-addition-calculator" }
    ]
  },
  {
    id: "electromagnetism",
    title: "Electromagnetism calculators 🧲",
    icon: Zap,
    calculators: [
      { name: "Acceleration in the Electric Field Calculator", slug: "acceleration-in-electric-field-calculator" },
      { name: "AC Wattage Calculator", slug: "ac-wattage-calculator" },
      { name: "Capacitance Calculator", slug: "capacitance-calculator" },
      { name: "Capacitive Reactance Calculator", slug: "capacitive-reactance-calculator" },
      { name: "Conductivity to Resistivity Calculator", slug: "conductivity-to-resistivity-calculator" },
      { name: "Coulomb's Law Calculator", slug: "coulombs-law-calculator" },
      { name: "Cutoff Frequency Calculator", slug: "cutoff-frequency-calculator" },
      { name: "Cyclotron Frequency Calculator", slug: "cyclotron-frequency-calculator" },
      { name: "Debye Length Calculator", slug: "debye-length-calculator" },
      { name: "Delta to Wye Conversion Calculator", slug: "delta-to-wye-conversion-calculator" },
      { name: "Dipole Moment Calculator", slug: "dipole-moment-calculator" },
      { name: "Drift Velocity Calculator", slug: "drift-velocity-calculator" },
      { name: "Electrical Power Calculator", slug: "electrical-power-calculator" },
      { name: "Electric Field Calculator", slug: "electric-field-calculator" },
      { name: "Electric Motor Torque Calculator", slug: "electric-motor-torque-calculator" },
      { name: "Electric Potential Calculator", slug: "electric-potential-calculator" },
      { name: "Energy Density of Fields Calculator", slug: "energy-density-of-fields-calculator" },
      { name: "Excess Electrons Calculator", slug: "excess-electrons-calculator" },
      { name: "Faraday's Law Calculator", slug: "faradays-law-calculator" },
      { name: "Free Space Path Loss Calculator", slug: "free-space-path-loss-calculator" },
      { name: "Frequency Bandwidth Calculator", slug: "frequency-bandwidth-calculator" },
      { name: "Fresnel Zone Calculator", slug: "fresnel-zone-calculator" },
      { name: "Gauss's Law Calculator", slug: "gausss-law-calculator" },
      { name: "Hall Coefficient Calculator", slug: "hall-coefficient-calculator" },
      { name: "HP to Amps Calculator", slug: "hp-to-amps-calculator" },
      { name: "Inductive Reactance Calculator", slug: "inductive-reactance-calculator" },
      { name: "Insertion Loss Calculator", slug: "insertion-loss-calculator" },
      { name: "Internal Resistance Calculator", slug: "internal-resistance-calculator" },
      { name: "kVA Calculator", slug: "kva-calculator" },
      { name: "Lorentz Force Calculator", slug: "lorentz-force-calculator" },
      { name: "Magnetic Declination Calculator", slug: "magnetic-declination-calculator" },
      { name: "Magnetic Dipole Moment Calculator", slug: "magnetic-dipole-moment-calculator" },
      { name: "Magnetic Field of Straight Wire Calculator", slug: "magnetic-field-of-straight-wire-calculator" },
      { name: "Magnetic Permeability Calculator", slug: "magnetic-permeability-calculator" },
      { name: "Power Dissipation Calculator", slug: "power-dissipation-calculator" },
      { name: "Power Factor Calculator", slug: "power-factor-calculator" },
      { name: "Skin Depth Calculator", slug: "skin-depth-calculator" },
      { name: "Voltage Drop Calculator", slug: "voltage-drop-calculator" },
      { name: "Volt to Electron Volt Calculator", slug: "volt-to-electron-volt-calculator" },
      { name: "VSWR Calculator", slug: "vswr-calculator" },
      { name: "Watt Calculator", slug: "watt-calculator" },
      { name: "Watt-hour Calculator", slug: "watt-hour-calculator" },
      { name: "Watts to Amps Calculator", slug: "watts-to-amps-calculator" },
      { name: "Watts to Lux Calculator", slug: "watts-to-lux-calculator" }
    ]
  },
  {
    id: "electronics-circuits",
    title: "Electronics and circuits calculators 💡",
    icon: Cpu,
    calculators: [
      { name: "Boost Converter Calculator", slug: "boost-converter-calculator" },
      { name: "Breaker Size Calculator", slug: "breaker-size-calculator" },
      { name: "Bridge Rectifier Calculator", slug: "bridge-rectifier-calculator" },
      { name: "Buck Converter Calculator", slug: "buck-converter-calculator" },
      { name: "Capacitive Transformerless Power Supply Calculator", slug: "capacitive-transformerless-power-supply-calculator" },
      { name: "Capacitor Charge Time Calculator", slug: "capacitor-charge-time-calculator" },
      { name: "Capacitor Calculator", slug: "capacitor-calculator" },
      { name: "Capacitor Energy Calculator", slug: "capacitor-energy-calculator" },
      { name: "Capacitors in Series Calculator", slug: "capacitors-in-series-calculator" },
      { name: "Capacitor Size Calculator", slug: "capacitor-size-calculator" },
      { name: "Crossover Calculator", slug: "crossover-calculator" },
      { name: "Current Divider Calculator", slug: "current-divider-calculator" },
      { name: "Dipole Calculator", slug: "dipole-antenna-calculator" },
      { name: "Flyback Converter Calculator", slug: "flyback-converter-calculator" },
      { name: "Forward Converter Calculator", slug: "forward-converter-calculator" },
      { name: "Generator Power Calculator", slug: "generator-power-calculator" },
      { name: "Helical Coil Calculator", slug: "helical-coil-calculator" },
      { name: "High Pass Filter Calculator", slug: "high-pass-filter-calculator" },
      { name: "Ideal Transformer Calculator", slug: "ideal-transformer-calculator" },
      { name: "Inductor Energy Storage Calculator", slug: "inductor-energy-storage-calculator" },
      { name: "Inductors in Parallel Calculator", slug: "inductors-in-parallel-calculator" },
      { name: "Inductors In Series Calculator", slug: "inductors-in-series-calculator" },
      { name: "Inverting Buck-Boost Converter Calculator", slug: "inverting-buck-boost-converter-calculator" },
      { name: "J-Pole Antenna Calculator", slug: "j-pole-antenna-calculator" },
      { name: "LED Resistor Calculator", slug: "led-resistor-calculator" },
      { name: "Low Pass Filter Calculator", slug: "low-pass-filter-calculator" },
      { name: "Magnetic Force Between Wires Calculator", slug: "magnetic-force-between-wires-calculator" },
      { name: "Magnetic Force on Wire Calculator", slug: "magnetic-force-on-wire-calculator" },
      { name: "MOSFET Calculator", slug: "mosfet-calculator" },
      { name: "MOSFET Threshold Voltage Calculator", slug: "mosfet-threshold-voltage-calculator" },
      { name: "555 Timer Calculator", slug: "555-timer-calculator" },
      { name: "Noise Figure Calculator", slug: "noise-figure-calculator" },
      { name: "Ohm's Law Calculator", slug: "ohms-law-calculator" },
      { name: "Parallel Capacitor Calculator", slug: "parallel-capacitor-calculator" },
      { name: "Parallel Resistor Calculator", slug: "parallel-resistor-calculator" },
      { name: "Photon Detection Efficiency Calculator", slug: "photon-detection-efficiency-calculator" },
      { name: "RC Circuit Calculator", slug: "rc-circuit-calculator" },
      { name: "Resistor Color Code Calculator", slug: "resistor-color-code-calculator" },
      { name: "Resistor Noise Calculator", slug: "resistor-noise-calculator" },
      { name: "Resistor Wattage Calculator", slug: "resistor-wattage-calculator" },
      { name: "Resonant Frequency Calculator", slug: "resonant-frequency-calculator" },
      { name: "RLC Circuit Calculator", slug: "rlc-circuit-calculator" },
      { name: "RLC Impedance Calculator", slug: "rlc-impedance-calculator" },
      { name: "RMS Voltage Calculator", slug: "rms-voltage-calculator" },
      { name: "Series Resistor Calculator", slug: "series-resistor-calculator" },
      { name: "Shockley Diode Calculator", slug: "shockley-diode-calculator" },
      { name: "Solenoid Inductance Calculator", slug: "solenoid-inductance-calculator" },
      { name: "Solenoid Magnetic Field Calculator", slug: "solenoid-magnetic-field-calculator" },
      { name: "Spherical Capacitor Calculator", slug: "spherical-capacitor-calculator" },
      { name: "Three Phase Calculator", slug: "three-phase-calculator" },
      { name: "Transformer Sizing Calculator", slug: "transformer-sizing-calculator" },
      { name: "Transistor Biasing Calculator", slug: "transistor-biasing-calculator" },
      { name: "Voltage Divider Calculator", slug: "voltage-divider-calculator" },
      { name: "Voltage Regulation Calculator", slug: "voltage-regulation-calculator" },
      { name: "Wheatstone Bridge Calculator", slug: "wheatstone-bridge-calculator" },
      { name: "Wire Gauge Calculator", slug: "wire-gauge-calculator" },
      { name: "Wire Resistance Calculator", slug: "wire-resistance-calculator" },
      { name: "Wire Size Calculator", slug: "wire-size-calculator" }
    ]
  },
  {
    id: "fluid-mechanics",
    title: "Fluid mechanics calculators 💧",
    icon: Droplets,
    calculators: [
      { name: "API Gravity Calculator", slug: "api-gravity-calculator" },
      { name: "Archimedes' Principle Calculator", slug: "archimedes-principle-calculator" },
      { name: "Bernoulli Equation Calculator", slug: "bernoulli-equation-calculator" },
      { name: "Broad Crested Weir Calculator", slug: "broad-crested-weir-calculator" },
      { name: "Buoyancy Calculator", slug: "buoyancy-calculator" },
      { name: "Coefficient of Discharge Calculator", slug: "coefficient-of-discharge-calculator" },
      { name: "Cv Flow Calculator", slug: "cv-flow-calculator" },
      { name: "Cv Calculator — Valve Flow Coefficient", slug: "cv-valve-flow-coefficient-calculator" },
      { name: "Darcy's Law Calculator", slug: "darcys-law-calculator" },
      { name: "Darcy Weisbach Calculator", slug: "darcy-weisbach-calculator" },
      { name: "Differential Pressure Calculator", slug: "differential-pressure-calculator" },
      { name: "Drag Equation Calculator", slug: "drag-equation-calculator" },
      { name: "Fan Calculator", slug: "fan-calculator" },
      { name: "Flow Rate Calculator", slug: "flow-rate-calculator" },
      { name: "Friction Factor Calculator", slug: "friction-factor-calculator" },
      { name: "Friction Loss Calculator", slug: "friction-loss-calculator" },
      { name: "Froude Number Calculator", slug: "froude-number-calculator" },
      { name: "Hydraulic Conductivity Calculator", slug: "hydraulic-conductivity-calculator" },
      { name: "Hydraulic Gradient Calculator", slug: "hydraulic-gradient-calculator" },
      { name: "Hydraulic Jump Calculator", slug: "hydraulic-jump-calculator" },
      { name: "Hydraulic Pressure Calculator", slug: "hydraulic-pressure-calculator" },
      { name: "Hydraulic Radius Calculator", slug: "hydraulic-radius-calculator" },
      { name: "Hydrostatic Pressure Calculator", slug: "hydrostatic-pressure-calculator" },
      { name: "Knudsen Number Calculator", slug: "knudsen-number-calculator" },
      { name: "Lift Coefficient Calculator", slug: "lift-coefficient-calculator" },
      { name: "Mach Number Calculator", slug: "mach-number-calculator" },
      { name: "Magnus Force Calculator", slug: "magnus-force-calculator" },
      { name: "Manometer Calculator", slug: "manometer-calculator" },
      { name: "Moisture Content Calculator", slug: "moisture-content-calculator" },
      { name: "Oblique Shock Calculator", slug: "oblique-shock-calculator" },
      { name: "Open Channel Flow Calculator", slug: "open-channel-flow-calculator" },
      { name: "Orifice Flow Calculator", slug: "orifice-flow-calculator" },
      { name: "Pipe Flow Calculator", slug: "pipe-flow-calculator" },
      { name: "Pipe Velocity Calculator", slug: "pipe-velocity-calculator" },
      { name: "Pneumatic Cylinder Force Calculator", slug: "pneumatic-cylinder-force-calculator" },
      { name: "Poise-Stokes Converter", slug: "poise-stokes-converter" },
      { name: "Poiseuille's Law Calculator", slug: "poiseuilles-law-calculator" },
      { name: "Porosity and Permeability Calculator", slug: "porosity-and-permeability-calculator" },
      { name: "Pounds per Minute Calculator", slug: "pounds-per-minute-calculator" },
      { name: "Prandtl Meyer Expansion Calculator", slug: "prandtl-meyer-expansion-calculator" },
      { name: "Prandtl Number Calculator", slug: "prandtl-number-calculator" },
      { name: "Refrigerant Capillary Tube Calculator", slug: "refrigerant-capillary-tube-calculator" },
      { name: "Reynolds Number Calculator", slug: "reynolds-number-calculator" },
      { name: "Stokes' Law Calculator", slug: "stokes-law-calculator" },
      { name: "Water Density Calculator", slug: "water-density-calculator" },
      { name: "Water Pressure at Depth Calculator", slug: "water-pressure-at-depth-calculator" },
      { name: "Water Viscosity Calculator", slug: "water-viscosity-calculator" },
      { name: "Wind Correction Angle Calculator", slug: "wind-correction-angle-calculator" },
      { name: "Wind Load Calculator", slug: "wind-load-calculator" },
      { name: "Y+ Calculator", slug: "y-plus-calculator" }
    ]
  },
  {
    id: "atmospheric-physics",
    title: "Atmospheric physics calculators ☁️",
    icon: Cloud,
    calculators: [
      { name: "Absolute Humidity Calculator", slug: "absolute-humidity-calculator" },
      { name: "Air Density Calculator", slug: "air-density-calculator" },
      { name: "Air Pressure at Altitude Calculator", slug: "air-pressure-at-altitude-calculator" },
      { name: "Cloud Base Calculator", slug: "cloud-base-calculator" },
      { name: "Density Altitude Calculator", slug: "density-altitude-calculator" },
      { name: "Dew Point Calculator", slug: "dew-point-calculator" },
      { name: "Heat Index Calculator", slug: "heat-index-calculator" },
      { name: "Kinematic Viscosity of Air Calculator", slug: "kinematic-viscosity-of-air-calculator" },
      { name: "Lightning Distance Calculator", slug: "lightning-distance-calculator" },
      { name: "Mixing Ratio of Air Calculator", slug: "mixing-ratio-of-air-calculator" },
      { name: "Psychrometric Calculator", slug: "psychrometric-calculator" },
      { name: "Relative Humidity Calculator", slug: "relative-humidity-calculator" },
      { name: "SCFM Calculator", slug: "scfm-calculator" },
      { name: "Temperature at Altitude Calculator", slug: "temperature-at-altitude-calculator" },
      { name: "True Airspeed Calculator", slug: "true-airspeed-calculator" },
      { name: "Virtual Temperature Calculator", slug: "virtual-temperature-calculator" },
      { name: "Wet Bulb Calculator", slug: "wet-bulb-calculator" }
    ]
  },
  {
    id: "thermodynamics-heat",
    title: "Thermodynamics and heat calculators 🌡️",
    icon: Thermometer,
    calculators: [
      { name: "Biot Number Calculator", slug: "biot-number-calculator" },
      { name: "Boltzmann Factor Calculator", slug: "boltzmann-factor-calculator" },
      { name: "Boyle's Law Calculator", slug: "boyles-law-calculator" },
      { name: "BTU to Tons Converter", slug: "btu-to-tons-converter" },
      { name: "Calorimetry Calculator", slug: "calorimetry-calculator" },
      { name: "Carnot Efficiency Calculator", slug: "carnot-efficiency-calculator" },
      { name: "Charles' Law Calculator", slug: "charles-law-calculator" },
      { name: "Coefficient of Performance Calculator", slug: "coefficient-of-performance-calculator" },
      { name: "Compressibility Factor Calculator", slug: "compressibility-factor-calculator" },
      { name: "Curie's Law Calculator", slug: "curies-law-calculator" },
      { name: "Effectiveness-NTU Calculator", slug: "effectiveness-ntu-calculator" },
      { name: "Efficiency Calculator", slug: "efficiency-calculator" },
      { name: "Electrical Mobility Calculator", slug: "electrical-mobility-calculator" },
      { name: "Enthalpy Calculator", slug: "enthalpy-calculator" },
      { name: "Evaporation Rate Calculator", slug: "evaporation-rate-calculator" },
      { name: "Gay-Lussac's Law Calculator", slug: "gay-lussacs-law-calculator" },
      { name: "Heat Capacity Calculator", slug: "heat-capacity-calculator" },
      { name: "Heat Transfer Calculator", slug: "heat-transfer-calculator" },
      { name: "Heat Transfer Coefficient Calculator", slug: "heat-transfer-coefficient-calculator" },
      { name: "Ideal Gas Density Calculator", slug: "ideal-gas-density-calculator" },
      { name: "Ideal Gas Law Calculator", slug: "ideal-gas-law-calculator" },
      { name: "Isentropic Flow Calculator", slug: "isentropic-flow-calculator" },
      { name: "Joule Heating Calculator", slug: "joule-heating-calculator" },
      { name: "Latent Heat Calculator", slug: "latent-heat-calculator" },
      { name: "LMTD Calculator", slug: "lmtd-calculator" },
      { name: "Mean Free Path Calculator", slug: "mean-free-path-calculator" },
      { name: "Mixed Air Calculator", slug: "mixed-air-calculator" },
      { name: "Mixed Air Temperature Calculator", slug: "mixed-air-temperature-calculator" },
      { name: "Newton's Law of Cooling Calculator", slug: "newtons-law-of-cooling-calculator" },
      { name: "Nusselt Number Calculator", slug: "nusselt-number-calculator" },
      { name: "Particles Velocity Calculator", slug: "particles-velocity-calculator" },
      { name: "Root Mean Square Velocity Calculator", slug: "root-mean-square-velocity-calculator" },
      { name: "Sensible Heat Calculator", slug: "sensible-heat-calculator" },
      { name: "Specific Gas Constant Calculator", slug: "specific-gas-constant-calculator" },
      { name: "Specific Heat Calculator", slug: "specific-heat-calculator" },
      { name: "Thermal Conductivity Calculator", slug: "thermal-conductivity-calculator" },
      { name: "Thermal Diffusivity Calculator", slug: "thermal-diffusivity-calculator" },
      { name: "Thermal Efficiency Calculator", slug: "thermal-efficiency-calculator" },
      { name: "Thermal Energy Calculator", slug: "thermal-energy-calculator" },
      { name: "Thermal Equilibrium Calculator", slug: "thermal-equilibrium-calculator" },
      { name: "Thermal Expansion Calculator", slug: "thermal-expansion-calculator" },
      { name: "Thermal Resistance Calculator", slug: "thermal-resistance-calculator" },
      { name: "Combined Gas Law Calculator", slug: "combined-gas-law-calculator" },
      { name: "Van der Waals Equation Calculator", slug: "van-der-waals-equation-calculator" },
      { name: "Water Heating Calculator", slug: "water-heating-calculator" },
      { name: "Watts to Heat Calculator", slug: "watts-to-heat-calculator" }
    ]
  },
  {
    id: "quantum-mechanics",
    title: "Quantum mechanics calculators ⚛️",
    icon: Atom,
    calculators: [
      { name: "Bohr Model Calculator", slug: "bohr-model-calculator" },
      { name: "Compton Scattering Calculator", slug: "compton-scattering-calculator" },
      { name: "Compton Wavelength Calculator", slug: "compton-wavelength-calculator" },
      { name: "Curie Constant Calculator", slug: "curie-constant-calculator" },
      { name: "De Broglie Wavelength Calculator", slug: "de-broglie-wavelength-calculator" },
      { name: "Fermi Level Calculator", slug: "fermi-level-calculator" },
      { name: "Frequency of Light Calculator", slug: "frequency-of-light-calculator" },
      { name: "Heisenberg's Uncertainty Principle Calculator", slug: "heisenbergs-uncertainty-principle-calculator" },
      { name: "Hydrogen Energy Levels Calculator", slug: "hydrogen-energy-levels-calculator" },
      { name: "Magnetic Moment Calculator", slug: "magnetic-moment-calculator" },
      { name: "Photoelectric Effect Calculator", slug: "photoelectric-effect-calculator" },
      { name: "Photon Energy Calculator", slug: "photon-energy-calculator" },
      { name: "Rydberg Equation Calculator", slug: "rydberg-equation-calculator" },
      { name: "Stefan Boltzmann Law Calculator", slug: "stefan-boltzmann-law-calculator" },
      { name: "Wien's Law Calculator", slug: "wiens-law-calculator" }
    ]
  },
  {
    id: "everyday-physics",
    title: "Everyday physics and experiments calculators 👩‍🔬",
    icon: FlaskConical,
    calculators: [
      { name: "Buoyancy Experiment Calculator", slug: "buoyancy-experiment-calculator" },
      { name: "Flat vs. Round Earth Calculator", slug: "flat-vs-round-earth-calculator" },
      { name: "Hair Diffraction Calculator", slug: "hair-diffraction-calculator" },
      { name: "Immersed Weight Calculator", slug: "immersed-weight-calculator" },
      { name: "Projectile Motion Experiment Calculator", slug: "projectile-motion-experiment-calculator" },
      { name: "Smartphone Projector Calculator", slug: "smartphone-projector-calculator" },
      { name: "Sun Angle Calculator", slug: "sun-angle-calculator" },
      { name: "Sunrise Sunset Calculator", slug: "sunrise-sunset-calculator" }
    ]
  },
  {
    id: "other-physics",
    title: "Other physics calculators 🔬",
    icon: Beaker,
    calculators: [
      { name: "Attenuation Calculator", slug: "attenuation-calculator" },
      { name: "Blast Radius Calculator", slug: "blast-radius-calculator" },
      { name: "Exoplanet Travel Planner Calculator", slug: "exoplanet-travel-planner-calculator" },
      { name: "Inverse Square Law Calculator", slug: "inverse-square-law-calculator" },
      { name: "Quantum Number Calculator", slug: "quantum-number-calculator" },
      { name: "Reaction Time Calculator", slug: "reaction-time-calculator" },
      { name: "Surface Tension Calculator", slug: "surface-tension-calculator" },
      { name: "Warp Speed Calculator", slug: "warp-speed-calculator" }
    ]
  }
];
