import { Activity, TrendingUp, Timer, HelpCircle, Trophy } from 'lucide-react';

export const STATISTICS_DATA = [
  {
    id: "descriptive-statistics",
    title: "Descriptive Statistics 📊",
    icon: Activity,
    calculators: [
      { name: "Mean, Median, Mode Calculator", slug: "mean-median-mode-calculator" },
      { name: "Standard Deviation Calculator", slug: "standard-deviation-calculator" },
      { name: "Variance Calculator", slug: "variance-calculator" },
      { name: "Range Calculator", slug: "range-calculator" },
      { name: "Interquartile Range (IQR) Calculator", slug: "interquartile-range-calculator" },
      { name: "Mean Absolute Deviation (MAD) Calculator", slug: "mean-absolute-deviation-calculator" },
      { name: "Skewness Calculator", slug: "skewness-calculator" },
      { name: "Kurtosis Calculator", slug: "kurtosis-calculator" },
      { name: "Quartile Calculator", slug: "quartile-calculator" },
      { name: "Percentile Calculator", slug: "percentile-calculator" },
      { name: "Decile Calculator", slug: "decile-calculator" },
      { name: "Coefficient of Variation (CV) Calculator", slug: "coefficient-of-variation-calculator" },
      { name: "Geometric Mean Calculator", slug: "geometric-mean-calculator" },
      { name: "Harmonic Mean Calculator", slug: "harmonic-mean-calculator" },
      { name: "Quadratic Mean (RMS) Calculator", slug: "quadratic-mean-rms-calculator" },
      { name: "Weighted Mean Calculator", slug: "weighted-mean-calculator" },
      { name: "Midrange Calculator", slug: "midrange-calculator" },
      { name: "Trimmed Mean Calculator", slug: "trimmed-mean-calculator" },
      { name: "Outlier Calculator (IQR Method)", slug: "outlier-calculator-iqr" },
      { name: "Absolute Deviation Calculator", slug: "absolute-deviation-calculator" }
    ]
  },
  {
    id: "probability-combinatorics",
    title: "Probability & Combinatorics 🎲",
    icon: HelpCircle,
    calculators: [
      { name: "Basic Probability Calculator", slug: "basic-probability-calculator" },
      { name: "Odds Calculator (Probability to Odds)", slug: "odds-calculator" },
      { name: "Permutations Calculator (nPr)", slug: "permutations-calculator-npr" },
      { name: "Combinations Calculator (nCr)", slug: "combinations-calculator-ncr" },
      { name: "Bayes' Theorem Calculator", slug: "bayes-theorem-calculator" },
      { name: "Expected Value Calculator", slug: "expected-value-calculator" },
      { name: "Variance of a Random Variable Calculator", slug: "variance-random-variable-calculator" },
      { name: "Binomial Probability Calculator", slug: "binomial-probability-calculator" },
      { name: "Poisson Probability Calculator", slug: "poisson-probability-calculator" },
      { name: "Hypergeometric Probability Calculator", slug: "hypergeometric-probability-calculator" },
      { name: "Geometric Probability Calculator", slug: "geometric-probability-calculator" },
      { name: "Negative Binomial Probability Calculator", slug: "negative-binomial-probability-calculator" },
      { name: "Multinomial Probability Calculator", slug: "multinomial-probability-calculator" },
      { name: "Normal Distribution (Z-Score to Prob) Calculator", slug: "normal-distribution-calculator" },
      { name: "Standard Normal Distribution (Z-Table) Calculator", slug: "standard-normal-distribution-calculator" },
      { name: "Student's t-Distribution Calculator", slug: "students-t-distribution-calculator" },
      { name: "Chi-Square Distribution Calculator", slug: "chi-square-distribution-calculator" },
      { name: "F-Distribution Calculator", slug: "f-distribution-calculator" },
      { name: "Uniform Distribution Calculator", slug: "uniform-distribution-calculator" },
      { name: "Exponential Distribution Calculator", slug: "exponential-distribution-calculator" },
      { name: "Log-Normal Distribution Calculator", slug: "log-normal-distribution-calculator" },
      { name: "Beta Distribution Calculator", slug: "beta-distribution-calculator" }
    ]
  },
  {
    id: "hypothesis-testing",
    title: "Statistical Hypothesis Tests 🔬",
    icon: Trophy,
    calculators: [
      { name: "One-Sample z-Test Calculator", slug: "one-sample-z-test-calculator" },
      { name: "Two-Sample z-Test Calculator", slug: "two-sample-z-test-calculator" },
      { name: "One-Sample t-Test Calculator", slug: "one-sample-t-test-calculator" },
      { name: "Two-Sample t-Test (Equal Variance) Calculator", slug: "two-sample-t-test-equal-variance" },
      { name: "Two-Sample t-Test (Unequal Variance) Calculator", slug: "two-sample-t-test-unequal-variance" },
      { name: "Paired t-Test Calculator", slug: "paired-t-test-calculator" },
      { name: "Chi-Square Goodness of Fit Test Calculator", slug: "chi-square-goodness-of-fit-test" },
      { name: "Chi-Square Test of Independence Calculator", slug: "chi-square-test-of-independence" },
      { name: "Fisher's Exact Test Calculator", slug: "fishers-exact-test" },
      { name: "McNemar's Test Calculator", slug: "mcnemars-test-calculator" },
      { name: "One-Way ANOVA Calculator", slug: "one-way-anova-calculator" },
      { name: "Two-Way ANOVA Calculator", slug: "two-way-anova-calculator" },
      { name: "Mann-Whitney U Test Calculator", slug: "mann-whitney-u-test" },
      { name: "Wilcoxon Signed-Rank Test Calculator", slug: "wilcoxon-signed-rank-test" },
      { name: "Kruskal-Wallis Test Calculator", slug: "kruskal-wallis-test" },
      { name: "Friedman Test Calculator", slug: "friedman-test" },
      { name: "F-Test for Equality of Variances Calculator", slug: "f-test-equality-of-variances" },
      { name: "Z-Score to P-Value Calculator", slug: "z-score-to-p-value" },
      { name: "T-Score to P-Value Calculator", slug: "t-score-to-p-value" },
      { name: "Chi-Square to P-Value Calculator", slug: "chi-square-to-p-value" },
      { name: "F-Statistic to P-Value Calculator", slug: "f-statistic-to-p-value" },
      { name: "Post-hoc Tukey HSD Calculator", slug: "post-hoc-tukey-hsd" },
      { name: "Bonferroni Correction Calculator", slug: "bonferroni-correction-calculator" },
      { name: "Benjamini-Hochberg (FDR) Calculator", slug: "benjamini-hochberg-fdr" },
      { name: "Outlier Test (Grubbs' Test) Calculator", slug: "outlier-test-grubbs" },
      { name: "Outlier Test (Dixon's Q-Test) Calculator", slug: "outlier-test-dixons-q" }
    ]
  },
  {
    id: "correlation-regression",
    title: "Correlation & Regression 📈",
    icon: TrendingUp,
    calculators: [
      { name: "Pearson Correlation Coefficient Calculator", slug: "pearson-correlation-coefficient" },
      { name: "Spearman's Rank Correlation Calculator", slug: "spearmans-rank-correlation" },
      { name: "Covariance Calculator", slug: "covariance-calculator" },
      { name: "Simple Linear Regression Calculator", slug: "simple-linear-regression" },
      { name: "Multiple Linear Regression Calculator", slug: "multiple-linear-regression" },
      { name: "R-Squared Calculator", slug: "r-squared-calculator" },
      { name: "Adjusted R-Squared Calculator", slug: "adjusted-r-squared-calculator" },
      { name: "Standard Error of the Estimate Calculator", slug: "standard-error-estimate" },
      { name: "Residuals Calculator", slug: "residuals-calculator" },
      { name: "Residual Sum of Squares (RSS) Calculator", slug: "residual-sum-of-squares" },
      { name: "Total Sum of Squares (TSS) Calculator", slug: "total-sum-of-squares" },
      { name: "Explained Sum of Squares (ESS) Calculator", slug: "explained-sum-of-squares" },
      { name: "Exponential Regression Calculator", slug: "exponential-regression" },
      { name: "Logarithmic Regression Calculator", slug: "logarithmic-regression" },
      { name: "Power Regression Calculator", slug: "power-regression" },
      { name: "Quadratic Regression Calculator", slug: "quadratic-regression" },
      { name: "Logistic Regression Calculator", slug: "logistic-regression" },
      { name: "Trend Line Calculator", slug: "trend-line-calculator" },
      { name: "Autocorrelation Calculator", slug: "autocorrelation-calculator" },
      { name: "Durbin-Watson Statistic Calculator", slug: "durbin-watson-statistic" },
      { name: "Partial Correlation Calculator", slug: "partial-correlation-calculator" },
      { name: "Semi-Partial Correlation Calculator", slug: "semi-partial-correlation-calculator" },
      { name: "Standardized Beta Coefficient Calculator", slug: "standardized-beta-coefficient" },
      { name: "Path Coefficient Calculator", slug: "path-coefficient-calculator" }
    ]
  },
  {
    id: "confidence-intervals",
    title: "Confidence Intervals & Estimation ⏱️",
    icon: Timer,
    calculators: [
      { name: "Confidence Interval for the Mean (Known SD) Calculator", slug: "confidence-interval-mean-known-sd" },
      { name: "Confidence Interval for the Mean (Unknown SD) Calculator", slug: "confidence-interval-mean-unknown-sd" },
      { name: "Confidence Interval for a Proportion Calculator", slug: "confidence-interval-proportion" },
      { name: "Confidence Interval for Two Means (Independent) Calculator", slug: "confidence-interval-two-means-independent" },
      { name: "Confidence Interval for Two Means (Paired) Calculator", slug: "confidence-interval-two-means-paired" },
      { name: "Confidence Interval for Two Proportions Calculator", slug: "confidence-interval-two-proportions" },
      { name: "Confidence Interval for Variance & SD Calculator", slug: "confidence-interval-variance-sd" },
      { name: "Margin of Error Calculator", slug: "margin-of-error-calculator" },
      { name: "Sample Size Calculator (for Estimating Mean)", slug: "sample-size-calculator-mean" },
      { name: "Sample Size Calculator (for Estimating Proportion)", slug: "sample-size-calculator-proportion" },
      { name: "Sample Size Calculator (for A/B Testing)", slug: "sample-size-calculator-ab-testing" },
      { name: "Statistical Power Analysis Calculator", slug: "statistical-power-analysis" },
      { name: "Standard Error of the Mean Calculator", slug: "standard-error-mean-calculator" },
      { name: "Standard Error of the Proportion Calculator", slug: "standard-error-proportion" },
      { name: "Standard Error of Two Means Difference Calculator", slug: "standard-error-two-means-difference" },
      { name: "Standard Error of Two Proportions Difference Calculator", slug: "standard-error-two-proportions-difference" },
      { name: "Pooled Variance Calculator", slug: "pooled-variance-calculator" },
      { name: "Effect Size (Cohen's d) Calculator", slug: "effect-size-cohens-d" },
      { name: "Effect Size (Eta-Squared) Calculator", slug: "effect-size-eta-squared" },
      { name: "Expected Value of Information Calculator", slug: "expected-value-of-information" }
    ]
  },
  {
    id: "data-science",
    title: "Advanced Data Science & Analytics 🧠",
    icon: Activity,
    calculators: [
      { name: "Confusion Matrix Calculator", slug: "confusion-matrix-calculator" },
      { name: "Sensitivity (Recall) and Specificity Calculator", slug: "sensitivity-specificity-calculator" },
      { name: "Precision and F1 Score Calculator", slug: "precision-f1-score-calculator" },
      { name: "ROC Curve AUC Calculator", slug: "roc-curve-auc" },
      { name: "Jaccard Similarity Calculator", slug: "jaccard-similarity-calculator" },
      { name: "Cosine Similarity Calculator", slug: "cosine-similarity-calculator" },
      { name: "Euclidean Distance Calculator", slug: "euclidean-distance-calculator" },
      { name: "Manhattan Distance Calculator", slug: "manhattan-distance-calculator" },
      { name: "Chebyshev Distance Calculator", slug: "chebyshev-distance-calculator" },
      { name: "Minkowski Distance Calculator", slug: "minkowski-distance-calculator" },
      { name: "Gini Index / Coefficient Calculator", slug: "gini-index-coefficient" },
      { name: "Lorenz Curve Area Calculator", slug: "lorenz-curve-area-calculator" },
      { name: "Herfindahl-Hirschman Index (HHI) Calculator", slug: "herfindahl-hirschman-index" },
      { name: "Shannon Entropy Calculator", slug: "shannon-entropy-calculator" },
      { name: "Kullback-Leibler (KL) Divergence Calculator", slug: "kullback-leibler-kl-divergence" },
      { name: "Shannon-Wiener Diversity Index Calculator", slug: "shannon-wiener-diversity-index" },
      { name: "Simpson's Diversity Index Calculator", slug: "simpsons-diversity-index" },
      { name: "MAE (Mean Absolute Error) Calculator", slug: "mae-calculator" },
      { name: "MSE (Mean Squared Error) Calculator", slug: "mse-calculator" },
      { name: "RMSE (Root Mean Squared Error) Calculator", slug: "rmse-calculator" },
      { name: "MAPE (Mean Absolute Percentage Error) Calculator", slug: "mape-calculator" },
      { name: "ROUGE Score Calculator", slug: "rouge-score-calculator" }
    ]
  },
  {
    id: "indexing-other",
    title: "Other Statistical Measures & Indexing 📋",
    icon: HelpCircle,
    calculators: [
      { name: "Moving Average Calculator", slug: "moving-average-calculator" },
      { name: "Weighted Moving Average Calculator", slug: "weighted-moving-average" },
      { name: "Exponential Moving Average (EMA) Calculator", slug: "exponential-moving-average" },
      { name: "Single Exponential Smoothing Calculator", slug: "single-exponential-smoothing" },
      { name: "Double Exponential Smoothing Calculator", slug: "double-exponential-smoothing" },
      { name: "Cronbach's Alpha Calculator", slug: "cronbachs-alpha-calculator" },
      { name: "Cohen's Kappa Calculator", slug: "cohens-kappa-calculator" },
      { name: "Fleiss' Kappa Calculator", slug: "fleiss-kappa-calculator" },
      { name: "Split-Half Reliability Calculator", slug: "split-half-reliability" },
      { name: "Standard Error of Measurement (SEM) Calculator", slug: "standard-error-measurement" },
      { name: "phi Coefficient Calculator", slug: "phi-coefficient-calculator" },
      { name: "Cramer's V Calculator", slug: "cramers-v-calculator" },
      { name: "Contingency Coefficient Calculator", slug: "contingency-coefficient-calculator" },
      { name: "Kendall's Tau Calculator", slug: "kendalls-tau-calculator" },
      { name: "Goodman and Kruskal's Gamma Calculator", slug: "goodman-kruskals-gamma" },
      { name: "Yule's Q Calculator", slug: "yules-q-calculator" },
      { name: "Odds Ratio Calculator", slug: "odds-ratio-calculator-stats" },
      { name: "Relative Risk Calculator", slug: "relative-risk-calculator-stats" },
      { name: "Number Needed to Treat (NNT) Calculator", slug: "number-needed-to-treat" },
      { name: "Likelihood Ratio Calculator", slug: "likelihood-ratio-calculator" },
      { name: "Diagnostic Odds Ratio Calculator", slug: "diagnostic-odds-ratio" },
      { name: "Index of Qualitative Variation (IQV) Calculator", slug: "index-qualitative-variation" }
    ]
  }
];
